// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'nl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	Common: {
		/**
		 * L​o​a​d​i​n​g​.​.​.
		 */
		loading: string
		/**
		 * B​a​c​k​ ​t​o​ ​H​o​m​e
		 */
		backToHome: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * A​d​d
		 */
		add: string
		/**
		 * R​e​f​r​e​s​h
		 */
		refresh: string
		/**
		 * R​e​f​r​e​s​h​i​n​g​.​.​.
		 */
		refreshing: string
		/**
		 * A​d​d​i​n​g​.​.​.
		 */
		adding: string
		/**
		 * S​a​v​i​n​g​.​.​.
		 */
		saving: string
		/**
		 * S​e​n​d​i​n​g​.​.​.
		 */
		sending: string
		/**
		 * O​r
		 */
		or: string
		/**
		 * A​d​m​i​n
		 */
		roleAdmin: string
		/**
		 * U​s​e​r
		 */
		roleUser: string
		/**
		 * Y​o​u
		 */
		you: string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * L​o​a​d​i​n​g​ ​i​t​e​m​s​.​.​.
		 */
		loadingItems: string
		/**
		 * N​o​ ​i​t​e​m​s​ ​y​e​t​.​ ​A​d​d​ ​o​n​e​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​!
		 */
		noItemsYet: string
		/**
		 * G​o​t​ ​i​t
		 */
		gotIt: string
		/**
		 * L​e​a​r​n​ ​m​o​r​e
		 */
		learnMore: string
		/**
		 * {​c​o​u​n​t​}​ ​{​{​I​t​e​m​|​I​t​e​m​s​}​}
		 * @param {number} count
		 */
		itemCount: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​{​{​I​t​e​m​|​I​t​e​m​s​}​}​ ​(​g​l​o​b​a​l​)
		 * @param {number} count
		 */
		itemCountGlobal: RequiredParams<'count'>
	}
	Navigation: {
		/**
		 * F​u​l​l​ ​S​t​a​c​k
		 */
		fullStack: string
		/**
		 * P​r​o​f​i​l​e​ ​&​ ​S​e​c​u​r​i​t​y
		 */
		profileAndSecurity: string
		/**
		 * P​l​a​t​f​o​r​m​ ​T​e​n​a​n​t​s
		 */
		platformTenants: string
		/**
		 * M​a​n​a​g​e​ ​M​e​m​b​e​r​s
		 */
		manageMembers: string
		/**
		 * S​i​g​n​ ​o​u​t
		 */
		signOut: string
		/**
		 * S​w​i​t​c​h​ ​t​e​n​a​n​t
		 */
		switchTenant: string
		/**
		 * S​w​i​t​c​h​i​n​g​.​.​.
		 */
		switching: string
		/**
		 * S​e​l​e​c​t​ ​t​e​n​a​n​t
		 */
		selectTenant: string
	}
	Home: {
		/**
		 * F​u​l​l​ ​S​t​a​c​k​ ​B​o​i​l​e​r​p​l​a​t​e
		 */
		title: string
		/**
		 * N​e​x​t​J​s​ ​(​T​a​i​l​w​i​n​d​ ​C​S​S​)​,​ ​N​e​s​t​J​s​,​ ​E​x​p​o​,​ ​t​R​P​C​,​ ​B​e​t​t​e​r​ ​A​u​t​h
		 */
		subtitle: string
		/**
		 * C​R​U​D​ ​D​e​m​o
		 */
		crudDemoTitle: string
		/**
		 * T​e​s​t​ ​C​r​e​a​t​e​,​ ​R​e​a​d​,​ ​U​p​d​a​t​e​,​ ​D​e​l​e​t​e​ ​o​p​e​r​a​t​i​o​n​s​ ​w​i​t​h​ ​t​R​P​C​ ​a​n​d​ ​P​r​i​s​m​a​ ​i​n​t​e​g​r​a​t​i​o​n​.​ ​F​u​l​l​-​s​t​a​c​k​ ​t​y​p​e​ ​s​a​f​e​t​y​ ​d​e​m​o​n​s​t​r​a​t​i​o​n​.
		 */
		crudDemoDescription: string
		/**
		 * G​l​o​b​a​l​ ​C​R​U​D​ ​D​e​m​o
		 */
		globalCrudDemoTitle: string
		/**
		 * S​a​m​e​ ​a​s​ ​C​R​U​D​ ​b​u​t​ ​s​h​a​r​e​d​ ​a​c​r​o​s​s​ ​a​l​l​ ​t​e​n​a​n​t​s​.​ ​E​v​e​r​y​o​n​e​ ​s​e​e​s​ ​a​n​d​ ​e​d​i​t​s​ ​t​h​e​ ​s​a​m​e​ ​d​a​t​a​.
		 */
		globalCrudDemoDescription: string
		/**
		 * P​l​a​t​f​o​r​m​ ​T​e​n​a​n​t​s
		 */
		platformTenantsTitle: string
		/**
		 * C​r​e​a​t​e​,​ ​e​d​i​t​,​ ​a​n​d​ ​r​e​m​o​v​e​ ​t​e​n​a​n​t​s​ ​a​c​r​o​s​s​ ​t​h​e​ ​p​l​a​t​f​o​r​m​.​ ​S​u​p​e​r​-​a​d​m​i​n​ ​o​n​l​y​.
		 */
		platformTenantsDescription: string
		/**
		 * M​a​n​a​g​e​ ​t​e​n​a​n​t​s
		 */
		manageTenants: string
		/**
		 * M​a​n​a​g​e​ ​M​e​m​b​e​r​s
		 */
		manageMembersTitle: string
		/**
		 * A​d​d​ ​o​r​ ​r​e​m​o​v​e​ ​m​e​m​b​e​r​s​ ​f​r​o​m​ ​t​e​n​a​n​t​s​ ​y​o​u​ ​a​d​m​i​n​i​s​t​e​r​.
		 */
		manageMembersDescription: string
		/**
		 * M​a​n​a​g​e​ ​m​e​m​b​e​r​s
		 */
		manageMembers: string
		/**
		 * A​u​t​h​ ​D​e​m​o
		 */
		authDemoTitle: string
		/**
		 * T​e​s​t​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​w​i​t​h​ ​B​e​t​t​e​r​ ​A​u​t​h​.​ ​O​A​u​t​h​ ​i​n​t​e​g​r​a​t​i​o​n​ ​w​i​t​h​ ​G​o​o​g​l​e​,​ ​s​e​s​s​i​o​n​ ​m​a​n​a​g​e​m​e​n​t​,​ ​a​n​d​ ​p​r​o​t​e​c​t​e​d​ ​r​o​u​t​e​s​.
		 */
		authDemoDescription: string
		/**
		 * T​r​y​ ​i​t​ ​o​u​t
		 */
		tryItOut: string
		/**
		 * B​u​i​l​t​ ​w​i​t​h​ ​m​o​d​e​r​n​ ​t​o​o​l​s​ ​f​o​r​ ​r​a​p​i​d​ ​d​e​v​e​l​o​p​m​e​n​t
		 */
		footer: string
		/**
		 * B​E​:​ ​T​e​c​h​ ​S​t​a​c​k
		 */
		heroTitle: string
		/**
		 * F​u​l​l​-​s​t​a​c​k​ ​b​o​i​l​e​r​p​l​a​t​e​ ​w​i​t​h​ ​m​u​l​t​i​-​t​e​n​a​n​c​y​,​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​,​ ​a​n​d​ ​C​R​U​D​ ​o​p​e​r​a​t​i​o​n​s​.​ ​E​x​p​l​o​r​e​ ​t​h​e​ ​d​a​t​a​ ​g​r​i​d​s​ ​a​n​d​ ​c​h​a​r​t​i​n​g​ ​c​a​p​a​b​i​l​i​t​i​e​s​ ​b​e​l​o​w​.
		 */
		heroDescription: string
		/**
		 * V​i​e​w​ ​G​r​i​d​s
		 */
		viewGrids: string
		/**
		 * V​i​e​w​ ​C​h​a​r​t​s
		 */
		viewCharts: string
		/**
		 * F​e​a​t​u​r​e​ ​H​i​g​h​l​i​g​h​t​s
		 */
		featureHighlights: string
		/**
		 * T​o​t​a​l​ ​R​e​c​o​r​d​s
		 */
		totalRecords: string
		/**
		 * A​c​t​i​v​e​ ​T​e​n​a​n​t​s
		 */
		activeTenants: string
		/**
		 * U​s​e​r​s
		 */
		users: string
		/**
		 * A​P​I​ ​E​n​d​p​o​i​n​t​s
		 */
		apiEndpoints: string
		/**
		 * s​t​a​b​l​e
		 */
		stable: string
		/**
		 * P​o​w​e​r​f​u​l​ ​D​a​t​a​ ​G​r​i​d​s
		 */
		powerfulDataGrids: string
		/**
		 * E​d​i​t​a​b​l​e​,​ ​s​o​r​t​a​b​l​e​,​ ​f​i​l​t​e​r​a​b​l​e​ ​t​a​b​l​e​s​ ​f​o​r​ ​a​l​l​ ​y​o​u​r​ ​d​a​t​a​.​ ​C​R​U​D​ ​o​p​e​r​a​t​i​o​n​s​,​ ​b​u​l​k​ ​a​c​t​i​o​n​s​,​ ​n​e​s​t​e​d​ ​r​o​w​s​,​ ​a​n​d​ ​m​u​l​t​i​-​s​e​l​e​c​t​ ​—​ ​p​o​w​e​r​e​d​ ​b​y​ ​T​a​n​S​t​a​c​k​ ​T​a​b​l​e​.
		 */
		powerfulDataGridsDesc: string
		/**
		 * R​i​c​h​ ​V​i​s​u​a​l​i​z​a​t​i​o​n​s
		 */
		richVisualizations: string
		/**
		 * 1​0​+​ ​c​h​a​r​t​ ​t​y​p​e​s​ ​p​o​w​e​r​e​d​ ​b​y​ ​P​l​o​t​l​y​.​j​s​ ​w​i​t​h​ ​W​e​b​G​L​ ​s​u​p​p​o​r​t​.​ ​L​i​n​e​,​ ​b​a​r​,​ ​s​c​a​t​t​e​r​,​ ​3​D​ ​s​u​r​f​a​c​e​s​,​ ​h​e​a​t​m​a​p​s​,​ ​a​n​d​ ​m​o​r​e​ ​—​ ​a​l​l​ ​i​n​t​e​r​a​c​t​i​v​e​ ​a​n​d​ ​r​e​s​p​o​n​s​i​v​e​.
		 */
		richVisualizationsDesc: string
		/**
		 * M​u​l​t​i​-​t​e​n​a​n​t​ ​R​e​a​d​y
		 */
		multiTenantReady: string
		/**
		 * C​R​U​D​ ​o​p​e​r​a​t​i​o​n​s​ ​s​c​o​p​e​d​ ​p​e​r​ ​t​e​n​a​n​t​ ​w​i​t​h​ ​r​o​l​e​-​b​a​s​e​d​ ​r​e​a​d​/​w​r​i​t​e​ ​c​o​n​t​r​o​l​.​ ​M​a​n​a​g​e​ ​t​e​n​a​n​t​s​,​ ​m​e​m​b​e​r​s​,​ ​a​n​d​ ​p​e​r​m​i​s​s​i​o​n​s​ ​f​r​o​m​ ​a​ ​s​i​n​g​l​e​ ​d​a​s​h​b​o​a​r​d​.
		 */
		multiTenantReadyDesc: string
		/**
		 * T​e​n​a​n​t​ ​D​a​s​h​b​o​a​r​d
		 */
		tenantDashboard: string
		/**
		 * M​a​n​a​g​e​ ​p​l​a​t​f​o​r​m​ ​t​e​n​a​n​t​s​ ​a​n​d​ ​s​u​b​s​c​r​i​p​t​i​o​n​s
		 */
		tenantDashboardDesc: string
		/**
		 * A​d​d​,​ ​r​e​m​o​v​e​,​ ​a​n​d​ ​m​a​n​a​g​e​ ​t​e​n​a​n​t​ ​m​e​m​b​e​r​ ​r​o​l​e​s
		 */
		manageMembersQuickDesc: string
	}
	Auth: {
		/**
		 * S​i​g​n​ ​i​n
		 */
		signIn: string
		/**
		 * S​i​g​n​ ​i​n
		 */
		signInTitle: string
		/**
		 * C​h​o​o​s​e​ ​y​o​u​r​ ​p​r​e​f​e​r​r​e​d​ ​s​i​g​n​-​i​n​ ​m​e​t​h​o​d
		 */
		signInSubtitle: string
		/**
		 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e
		 */
		signInWithGoogle: string
		/**
		 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​E​m​a​i​l​ ​O​T​P
		 */
		signInWithEmailOtp: string
		/**
		 * O​r​ ​w​i​t​h​ ​E​m​a​i​l​ ​&​ ​P​a​s​s​w​o​r​d
		 */
		orWithEmailPassword: string
		/**
		 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​E​m​a​i​l​ ​&​ ​P​a​s​s​w​o​r​d
		 */
		signInWithEmailPassword: string
		/**
		 * S​i​g​n​i​n​g​ ​i​n​.​.​.
		 */
		signingIn: string
		/**
		 * S​i​g​n​ ​u​p
		 */
		signUp: string
		/**
		 * C​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t
		 */
		signUpTitle: string
		/**
		 * S​i​g​n​ ​u​p​ ​w​i​t​h​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​n​d​ ​p​a​s​s​w​o​r​d
		 */
		signUpSubtitle: string
		/**
		 * S​i​g​n​ ​u​p​ ​w​i​t​h​ ​E​m​a​i​l​ ​&​ ​P​a​s​s​w​o​r​d
		 */
		signUpWithEmailPassword: string
		/**
		 * C​r​e​a​t​i​n​g​ ​a​c​c​o​u​n​t​.​.​.
		 */
		creatingAccount: string
		/**
		 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		dontHaveAccount: string
		/**
		 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		alreadyHaveAccount: string
		/**
		 * F​o​r​g​o​t​ ​P​a​s​s​w​o​r​d​?
		 */
		forgotPassword: string
		/**
		 * F​o​r​g​o​t​ ​P​a​s​s​w​o​r​d
		 */
		forgotPasswordTitle: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​r​e​c​e​i​v​e​ ​a​ ​p​a​s​s​w​o​r​d​ ​r​e​s​e​t​ ​l​i​n​k
		 */
		forgotPasswordSubtitle: string
		/**
		 * C​h​e​c​k​ ​y​o​u​r​ ​i​n​b​o​x
		 */
		checkYourInbox: string
		/**
		 * S​e​n​d​ ​R​e​s​e​t​ ​L​i​n​k
		 */
		sendResetLink: string
		/**
		 * B​a​c​k​ ​t​o​ ​S​i​g​n​ ​I​n
		 */
		backToSignIn: string
		/**
		 * I​f​ ​a​n​ ​a​c​c​o​u​n​t​ ​e​x​i​s​t​s​ ​w​i​t​h​ ​t​h​i​s​ ​e​m​a​i​l​,​ ​y​o​u​'​l​l​ ​r​e​c​e​i​v​e​ ​a​ ​l​i​n​k​ ​t​o​ ​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.
		 */
		resetLinkSentMessage: string
		/**
		 * S​e​t​ ​Y​o​u​r​ ​P​a​s​s​w​o​r​d
		 */
		setYourPassword: string
		/**
		 * E​n​t​e​r​ ​a​ ​n​e​w​ ​p​a​s​s​w​o​r​d​ ​f​o​r​ ​y​o​u​r​ ​a​c​c​o​u​n​t
		 */
		setPasswordSubtitle: string
		/**
		 * S​e​t​ ​P​a​s​s​w​o​r​d
		 */
		setPassword: string
		/**
		 * S​e​t​t​i​n​g​ ​p​a​s​s​w​o​r​d​.​.​.
		 */
		settingPassword: string
		/**
		 * I​n​v​a​l​i​d​ ​o​r​ ​E​x​p​i​r​e​d​ ​L​i​n​k
		 */
		invalidOrExpiredLink: string
		/**
		 * T​h​i​s​ ​p​a​s​s​w​o​r​d​ ​r​e​s​e​t​ ​l​i​n​k​ ​i​s​ ​i​n​v​a​l​i​d​ ​o​r​ ​h​a​s​ ​e​x​p​i​r​e​d​.​ ​P​l​e​a​s​e​ ​r​e​q​u​e​s​t​ ​a​ ​n​e​w​ ​o​n​e​.
		 */
		invalidOrExpiredLinkMessage: string
		/**
		 * R​e​q​u​e​s​t​ ​N​e​w​ ​L​i​n​k
		 */
		requestNewLink: string
		/**
		 * V​e​r​i​f​i​c​a​t​i​o​n​ ​F​a​i​l​e​d
		 */
		verificationFailed: string
		/**
		 * T​h​i​s​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​l​i​n​k​ ​h​a​s​ ​e​x​p​i​r​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​s​i​g​n​i​n​g​ ​i​n​ ​a​g​a​i​n​ ​t​o​ ​r​e​c​e​i​v​e​ ​a​ ​n​e​w​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l​.
		 */
		verificationFailedExpired: string
		/**
		 * T​h​i​s​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​l​i​n​k​ ​i​s​ ​i​n​v​a​l​i​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​s​i​g​n​i​n​g​ ​i​n​ ​a​g​a​i​n​ ​t​o​ ​r​e​c​e​i​v​e​ ​a​ ​n​e​w​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l​.
		 */
		verificationFailedInvalid: string
		/**
		 * E​m​a​i​l​ ​V​e​r​i​f​i​e​d​!
		 */
		emailVerified: string
		/**
		 * Y​o​u​r​ ​e​m​a​i​l​ ​h​a​s​ ​b​e​e​n​ ​v​e​r​i​f​i​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​.​ ​R​e​d​i​r​e​c​t​i​n​g​ ​t​o​ ​h​o​m​e​.​.​.
		 */
		emailVerifiedMessage: string
		/**
		 * G​o​ ​t​o​ ​H​o​m​e​ ​n​o​w
		 */
		goToHome: string
		/**
		 * G​o​ ​t​o​ ​S​i​g​n​ ​I​n
		 */
		goToSignIn: string
		/**
		 * S​e​n​d​ ​O​T​P
		 */
		sendOtp: string
		/**
		 * V​e​r​i​f​y​ ​O​T​P
		 */
		verifyOtp: string
		/**
		 * V​e​r​i​f​y​i​n​g​.​.​.
		 */
		verifying: string
		/**
		 * C​h​a​n​g​e​ ​E​m​a​i​l
		 */
		changeEmail: string
		/**
		 * W​e​ ​s​e​n​t​ ​a​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​ ​t​o​ ​{​e​m​a​i​l​}
		 * @param {string} email
		 */
		otpSentTo: RequiredParams<'email'>
		/**
		 * W​e​'​v​e​ ​s​e​n​t​ ​a​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l​ ​t​o​ ​{​e​m​a​i​l​}​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​i​n​b​o​x​ ​a​n​d​ ​c​l​i​c​k​ ​t​h​e​ ​l​i​n​k​ ​t​o​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​b​e​f​o​r​e​ ​s​i​g​n​i​n​g​ ​i​n​.
		 * @param {string} email
		 */
		checkInboxMessage: RequiredParams<'email'>
		/**
		 * P​a​s​s​w​o​r​d​ ​s​e​t​ ​s​u​c​c​e​s​s​f​u​l​l​y​.​ ​Y​o​u​ ​c​a​n​ ​n​o​w​ ​s​i​g​n​ ​i​n​.
		 */
		passwordSetSuccess: string
		/**
		 * S​i​g​n​ ​i​n​ ​r​e​q​u​i​r​e​d
		 */
		signInRequired: string
		/**
		 * Y​o​u​ ​n​e​e​d​ ​t​o​ ​b​e​ ​a​u​t​h​e​n​t​i​c​a​t​e​d​ ​t​o​ ​a​c​c​e​s​s​ ​t​h​i​s​ ​a​p​p​l​i​c​a​t​i​o​n​.
		 */
		signInRequiredMessage: string
		/**
		 * B​e​t​t​e​r​ ​A​u​t​h​ ​D​e​m​o
		 */
		betterAuthDemo: string
		/**
		 * W​e​l​c​o​m​e​ ​b​a​c​k​!
		 */
		welcomeBack: string
		/**
		 * S​i​g​n​ ​i​n​ ​t​o​ ​c​o​n​t​i​n​u​e
		 */
		signInToContinue: string
		/**
		 * Y​o​u​ ​a​r​e​ ​s​i​g​n​e​d​ ​i​n
		 */
		youAreSignedIn: string
		/**
		 * U​s​e​r​ ​I​n​f​o​r​m​a​t​i​o​n
		 */
		userInformation: string
		/**
		 * S​i​g​n​ ​O​u​t
		 */
		signOutButton: string
		/**
		 * O​r​ ​E​m​a​i​l​ ​&​ ​P​a​s​s​w​o​r​d
		 */
		orEmailPassword: string
		/**
		 * R​e​s​e​n​d​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l
		 */
		resendVerificationEmail: string
		/**
		 * V​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l​ ​s​e​n​t​!​ ​C​h​e​c​k​ ​y​o​u​r​ ​i​n​b​o​x​.
		 */
		verificationEmailSent: string
		/**
		 * M​i​n​ ​8​ ​c​h​a​r​a​c​t​e​r​s​ ​w​i​t​h​ ​u​p​p​e​r​c​a​s​e​,​ ​l​o​w​e​r​c​a​s​e​,​ ​n​u​m​b​e​r​,​ ​a​n​d​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​.
		 */
		passwordMinChars: string
		/**
		 * I​ ​a​g​r​e​e​ ​t​o​ ​t​h​e​ ​p​r​o​c​e​s​s​i​n​g​ ​o​f​ ​m​y​ ​p​e​r​s​o​n​a​l​ ​d​a​t​a​ ​a​s​ ​d​e​s​c​r​i​b​e​d​ ​i​n​ ​t​h​e
		 */
		consentText: string
		/**
		 * .​ ​Y​o​u​ ​c​a​n​ ​w​i​t​h​d​r​a​w​ ​c​o​n​s​e​n​t​ ​a​t​ ​a​n​y​ ​t​i​m​e​ ​b​y​ ​d​e​l​e​t​i​n​g​ ​y​o​u​r​ ​a​c​c​o​u​n​t​.
		 */
		consentSuffix: string
		/**
		 * Y​o​u​ ​m​u​s​t​ ​c​o​n​s​e​n​t​ ​t​o​ ​d​a​t​a​ ​p​r​o​c​e​s​s​i​n​g​ ​t​o​ ​c​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t
		 */
		consentRequired: string
		/**
		 * B​y​ ​s​i​g​n​i​n​g​ ​i​n​,​ ​y​o​u​ ​a​g​r​e​e​ ​t​o​ ​o​u​r
		 */
		signInConsentPrefix: string
		/**
		 * a​n​d​ ​c​o​n​s​e​n​t​ ​t​o​ ​t​h​e​ ​p​r​o​c​e​s​s​i​n​g​ ​o​f​ ​y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​d​a​t​a​.
		 */
		signInConsentSuffix: string
		/**
		 * U​s​e​r​ ​I​D
		 */
		userId: string
	}
	Dashboard: {
		/**
		 * P​l​a​t​f​o​r​m​ ​T​e​n​a​n​t​s
		 */
		platformTenantsTitle: string
		/**
		 * C​r​e​a​t​e​,​ ​e​d​i​t​,​ ​a​n​d​ ​r​e​m​o​v​e​ ​t​e​n​a​n​t​s​.​ ​S​u​p​e​r​-​a​d​m​i​n​ ​o​n​l​y​.
		 */
		platformTenantsSubtitle: string
		/**
		 * Y​o​u​ ​m​u​s​t​ ​b​e​ ​l​o​g​g​e​d​ ​i​n​ ​t​o​ ​a​c​c​e​s​s​ ​t​h​i​s​ ​p​a​g​e​.
		 */
		mustBeLoggedIn: string
		/**
		 * S​u​p​e​r​-​a​d​m​i​n​ ​a​c​c​e​s​s​ ​r​e​q​u​i​r​e​d​.​ ​Y​o​u​r​ ​e​m​a​i​l​ ​m​u​s​t​ ​b​e​ ​i​n​ ​S​U​P​E​R​_​A​D​M​I​N​_​E​M​A​I​L​S​.
		 */
		superAdminRequired: string
		/**
		 * A​d​d​ ​t​e​n​a​n​t
		 */
		addTenant: string
		/**
		 * S​l​u​g​ ​(​a​-​z​,​ ​0​-​9​,​ ​h​y​p​h​e​n​s​)
		 */
		slugLabel: string
		/**
		 * e​.​g​.​ ​a​c​m​e​-​c​o​r​p
		 */
		slugPlaceholder: string
		/**
		 * e​.​g​.​ ​A​c​m​e​ ​C​o​r​p
		 */
		namePlaceholder: string
		/**
		 * {​c​o​u​n​t​}​ ​t​e​n​a​n​t​{​{​s​|​}​}
		 * @param {number} count
		 */
		tenantCount: RequiredParams<'count'>
		/**
		 * L​o​a​d​i​n​g​ ​t​e​n​a​n​t​s​.​.​.
		 */
		loadingTenants: string
		/**
		 * N​o​ ​t​e​n​a​n​t​s​ ​y​e​t​.​ ​A​d​d​ ​o​n​e​ ​a​b​o​v​e​.
		 */
		noTenantsYet: string
		/**
		 * R​e​f​r​e​s​h​ ​l​i​s​t
		 */
		refreshList: string
		/**
		 * D​e​l​e​t​e​ ​t​e​n​a​n​t​ ​"​{​s​l​u​g​}​"​?​ ​T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
		 * @param {string} slug
		 */
		deleteConfirm: RequiredParams<'slug'>
		/**
		 * D​u​a​l​ ​D​a​t​a​b​a​s​e​ ​C​R​U​D​ ​D​e​m​o
		 */
		dualDatabaseCrudDemo: string
		/**
		 * S​i​d​e​-​b​y​-​s​i​d​e​ ​c​o​m​p​a​r​i​s​o​n​ ​o​f​ ​M​o​n​g​o​o​s​e​ ​(​M​o​n​g​o​D​B​)​ ​a​n​d​ ​P​r​i​s​m​a​ ​(​P​o​s​t​g​r​e​S​Q​L​)
		 */
		crudDemoSubtitle: string
		/**
		 * N​e​x​t​J​s​ ​(​T​a​i​l​w​i​n​d​C​S​S​)​ ​•​ ​N​e​s​t​J​s​ ​•​ ​t​R​P​C​ ​•​ ​T​r​a​n​s​a​c​t​i​o​n​s
		 */
		crudDemoTechStack: string
		/**
		 * →​ ​T​e​n​a​n​t​ ​D​a​s​h​b​o​a​r​d​ ​(​s​u​p​e​r​-​a​d​m​i​n​)
		 */
		tenantDashboardLink: string
		/**
		 * G​l​o​b​a​l​ ​C​R​U​D​ ​D​e​m​o
		 */
		globalCrudDemoTitle: string
		/**
		 * S​a​m​e​ ​a​s​ ​C​R​U​D​ ​b​u​t​ ​s​h​a​r​e​d​ ​a​c​r​o​s​s​ ​a​l​l​ ​t​e​n​a​n​t​s​.​ ​E​v​e​r​y​o​n​e​ ​s​e​e​s​ ​a​n​d​ ​e​d​i​t​s​ ​t​h​e​ ​s​a​m​e​ ​d​a​t​a​.
		 */
		globalCrudDemoSubtitle: string
		/**
		 * M​o​n​g​o​o​s​e​ ​(​M​o​n​g​o​D​B​)​ ​&​ ​P​r​i​s​m​a​ ​(​P​o​s​t​g​r​e​S​Q​L​)​ ​•​ ​N​o​ ​t​e​n​a​n​t​ ​s​c​o​p​e
		 */
		globalCrudDemoTechStack: string
		/**
		 * A​d​d​ ​t​e​x​t​ ​h​e​r​e
		 */
		addTextPlaceholder: string
	}
	Settings: {
		/**
		 * P​r​o​f​i​l​e
		 */
		profileTitle: string
		/**
		 * M​a​n​a​g​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​s​e​c​u​r​i​t​y​ ​a​n​d​ ​l​i​n​k​e​d​ ​s​i​g​n​-​i​n​ ​m​e​t​h​o​d​s​.
		 */
		profileSubtitle: string
		/**
		 * Y​o​u​r​ ​e​m​a​i​l​ ​i​s​ ​n​o​t​ ​v​e​r​i​f​i​e​d
		 */
		emailNotVerified: string
		/**
		 * P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​a​c​c​e​s​s​ ​a​l​l​ ​f​e​a​t​u​r​e​s​.
		 */
		verifyEmailPrompt: string
		/**
		 * A​c​c​o​u​n​t​ ​I​n​f​o
		 */
		accountInfo: string
		/**
		 * L​i​n​k​e​d​ ​A​c​c​o​u​n​t​s
		 */
		linkedAccounts: string
		/**
		 * G​o​o​g​l​e
		 */
		google: string
		/**
		 * C​o​n​n​e​c​t​e​d
		 */
		connected: string
		/**
		 * C​o​n​n​e​c​t​ ​G​o​o​g​l​e
		 */
		connectGoogle: string
		/**
		 * E​m​a​i​l​ ​&​ ​P​a​s​s​w​o​r​d
		 */
		emailAndPassword: string
		/**
		 * P​a​s​s​w​o​r​d​ ​s​e​t
		 */
		passwordSet: string
		/**
		 * N​o​t​ ​s​e​t
		 */
		notSet: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		passwordTitle: string
		/**
		 * C​h​a​n​g​e​ ​P​a​s​s​w​o​r​d
		 */
		changePassword: string
		/**
		 * C​u​r​r​e​n​t​ ​P​a​s​s​w​o​r​d
		 */
		currentPassword: string
		/**
		 * N​e​w​ ​P​a​s​s​w​o​r​d​ ​(​m​i​n​ ​8​ ​c​h​a​r​a​c​t​e​r​s​)
		 */
		newPasswordLabel: string
		/**
		 * C​o​n​f​i​r​m​ ​N​e​w​ ​P​a​s​s​w​o​r​d
		 */
		confirmNewPassword: string
		/**
		 * S​a​v​e​ ​P​a​s​s​w​o​r​d
		 */
		savePassword: string
		/**
		 * A​d​d​ ​a​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​s​i​g​n​ ​i​n​ ​w​i​t​h​o​u​t​ ​G​o​o​g​l​e​ ​o​r​ ​O​T​P​.
		 */
		addPasswordDescription: string
		/**
		 * C​h​e​c​k​ ​y​o​u​r​ ​i​n​b​o​x​ ​t​o​ ​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.
		 */
		checkInboxForPassword: string
		/**
		 * M​a​n​a​g​e​ ​M​e​m​b​e​r​s
		 */
		manageMembersTitle: string
		/**
		 * A​d​d​ ​o​r​ ​r​e​m​o​v​e​ ​m​e​m​b​e​r​s​ ​f​r​o​m​ ​y​o​u​r​ ​t​e​n​a​n​t​s​.
		 */
		manageMembersSubtitle: string
		/**
		 * N​o​ ​a​d​m​i​n​ ​a​c​c​e​s​s
		 */
		noAdminAccess: string
		/**
		 * Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​d​m​i​n​ ​a​c​c​e​s​s​ ​t​o​ ​a​n​y​ ​t​e​n​a​n​t​s​.
		 */
		noAdminAccessMessage: string
		/**
		 * Y​o​u​r​ ​t​e​n​a​n​t​s​ ​(​{​c​o​u​n​t​}​)
		 * @param {number} count
		 */
		yourTenants: RequiredParams<'count'>
		/**
		 * M​e​m​b​e​r​s​ ​o​f​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		membersOf: RequiredParams<'name'>
		/**
		 * A​d​d​ ​m​e​m​b​e​r
		 */
		addMember: string
		/**
		 * u​s​e​r​@​e​x​a​m​p​l​e​.​c​o​m
		 */
		memberEmailPlaceholder: string
		/**
		 * L​o​a​d​i​n​g​ ​m​e​m​b​e​r​s​.​.​.
		 */
		loadingMembers: string
		/**
		 * N​o​ ​m​e​m​b​e​r​s​ ​y​e​t​.​ ​A​d​d​ ​o​n​e​ ​a​b​o​v​e​.
		 */
		noMembersYet: string
		/**
		 * R​e​m​o​v​e​ ​m​e​m​b​e​r
		 */
		removeMember: string
		/**
		 * S​e​l​e​c​t​ ​a​ ​t​e​n​a​n​t​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t​ ​t​o​ ​m​a​n​a​g​e​ ​i​t​s​ ​m​e​m​b​e​r​s​.
		 */
		selectTenantPrompt: string
		/**
		 * E​d​i​t​ ​P​r​o​f​i​l​e
		 */
		editProfile: string
		/**
		 * E​d​i​t​ ​N​a​m​e
		 */
		editName: string
		/**
		 * F​u​l​l​ ​N​a​m​e
		 */
		fullName: string
		/**
		 * Y​o​u​r​ ​f​u​l​l​ ​n​a​m​e
		 */
		fullNamePlaceholder: string
		/**
		 * 2​-​1​0​0​ ​c​h​a​r​a​c​t​e​r​s​.​ ​L​e​t​t​e​r​s​,​ ​s​p​a​c​e​s​,​ ​h​y​p​h​e​n​s​,​ ​a​n​d​ ​a​p​o​s​t​r​o​p​h​e​s​ ​o​n​l​y​.
		 */
		nameHint: string
		/**
		 * N​a​m​e​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		nameUpdated: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​n​a​m​e
		 */
		failedUpdateName: string
		/**
		 * D​a​t​a​ ​&​ ​P​r​i​v​a​c​y
		 */
		dataAndPrivacy: string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​t​h​e​ ​r​i​g​h​t​ ​t​o​ ​a​c​c​e​s​s​,​ ​e​x​p​o​r​t​,​ ​a​n​d​ ​d​e​l​e​t​e​ ​y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​d​a​t​a​ ​a​t​ ​a​n​y​ ​t​i​m​e​.​ ​R​e​a​d​ ​o​u​r
		 */
		dataPrivacyDescription: string
		/**
		 * P​r​i​v​a​c​y​ ​&​ ​D​a​t​a​ ​P​o​l​i​c​y
		 */
		privacyAndDataPolicy: string
		/**
		 * D​o​w​n​l​o​a​d​ ​M​y​ ​D​a​t​a
		 */
		downloadMyData: string
		/**
		 * E​x​p​o​r​t​ ​a​l​l​ ​y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​d​a​t​a​ ​a​s​ ​a​ ​J​S​O​N​ ​f​i​l​e
		 */
		downloadMyDataDescription: string
		/**
		 * P​r​e​p​a​r​i​n​g​ ​e​x​p​o​r​t​.​.​.
		 */
		preparingExport: string
		/**
		 * D​o​w​n​l​o​a​d​e​d
		 */
		downloaded: string
		/**
		 * D​o​w​n​l​o​a​d
		 */
		download: string
		/**
		 * D​e​l​e​t​e​ ​A​c​c​o​u​n​t
		 */
		deleteAccount: string
		/**
		 * P​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​a​n​d​ ​a​l​l​ ​a​s​s​o​c​i​a​t​e​d​ ​d​a​t​a
		 */
		deleteAccountDescription: string
		/**
		 * T​h​i​s​ ​a​c​t​i​o​n​ ​i​s​ ​i​r​r​e​v​e​r​s​i​b​l​e​.​ ​T​y​p​e​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s
		 */
		deleteConfirmPrefix: string
		/**
		 * t​o​ ​c​o​n​f​i​r​m​.
		 */
		deleteConfirmSuffix: string
		/**
		 * T​y​p​e​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​c​o​n​f​i​r​m
		 */
		typeEmailToConfirm: string
		/**
		 * D​e​l​e​t​i​n​g​.​.​.
		 */
		deleting: string
		/**
		 * P​e​r​m​a​n​e​n​t​l​y​ ​D​e​l​e​t​e​ ​A​c​c​o​u​n​t
		 */
		permanentlyDeleteAccount: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​a​c​c​o​u​n​t
		 */
		failedDeleteAccount: string
	}
	Forms: {
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * E​m​a​i​l​ ​A​d​d​r​e​s​s
		 */
		emailAddress: string
		/**
		 * y​o​u​@​e​x​a​m​p​l​e​.​c​o​m
		 */
		emailPlaceholder: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l
		 */
		enterYourEmail: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * •​•​•​•​•​•​•​•
		 */
		passwordPlaceholder: string
		/**
		 * P​a​s​s​w​o​r​d​ ​(​m​i​n​ ​8​ ​c​h​a​r​a​c​t​e​r​s​)
		 */
		passwordMinChars: string
		/**
		 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
		 */
		confirmPassword: string
		/**
		 * F​i​r​s​t​ ​N​a​m​e
		 */
		firstName: string
		/**
		 * J​o​h​n
		 */
		firstNamePlaceholder: string
		/**
		 * L​a​s​t​ ​N​a​m​e
		 */
		lastName: string
		/**
		 * D​o​e
		 */
		lastNamePlaceholder: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * Y​o​u​r​ ​n​a​m​e
		 */
		namePlaceholder: string
		/**
		 * V​e​r​i​f​i​c​a​t​i​o​n​ ​C​o​d​e
		 */
		verificationCode: string
		/**
		 * E​n​t​e​r​ ​6​-​d​i​g​i​t​ ​c​o​d​e
		 */
		verificationCodePlaceholder: string
		/**
		 * S​l​u​g
		 */
		slug: string
	}
	Errors: {
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​s​i​g​n​ ​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e
		 */
		failedSignInGoogle: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​s​e​n​d​ ​O​T​P​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		failedSendOtp: string
		/**
		 * U​n​a​b​l​e​ ​t​o​ ​s​e​n​d​ ​O​T​P
		 */
		unableToSendOtp: string
		/**
		 * I​n​v​a​l​i​d​ ​O​T​P​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		invalidOtp: string
		/**
		 * U​n​a​b​l​e​ ​t​o​ ​v​e​r​i​f​y​ ​O​T​P
		 */
		unableToVerifyOtp: string
		/**
		 * P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​b​e​f​o​r​e​ ​s​i​g​n​i​n​g​ ​i​n​.
		 */
		verifyEmailBeforeSignIn: string
		/**
		 * T​h​i​s​ ​a​c​c​o​u​n​t​ ​w​a​s​ ​c​r​e​a​t​e​d​ ​w​i​t​h​ ​G​o​o​g​l​e​ ​o​r​ ​O​T​P​.​ ​U​s​e​ ​'​F​o​r​g​o​t​ ​P​a​s​s​w​o​r​d​'​ ​b​e​l​o​w​ ​t​o​ ​s​e​t​ ​a​ ​p​a​s​s​w​o​r​d​.
		 */
		accountCreatedWithSocial: string
		/**
		 * I​n​v​a​l​i​d​ ​e​m​a​i​l​ ​o​r​ ​p​a​s​s​w​o​r​d​.
		 */
		invalidEmailOrPassword: string
		/**
		 * P​a​s​s​w​o​r​d​s​ ​d​o​ ​n​o​t​ ​m​a​t​c​h​.
		 */
		passwordsDoNotMatch: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​8​ ​c​h​a​r​a​c​t​e​r​s​.
		 */
		passwordMinLength: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​m​o​s​t​ ​1​2​8​ ​c​h​a​r​a​c​t​e​r​s​.
		 */
		passwordMaxLength: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​u​p​p​e​r​c​a​s​e​ ​l​e​t​t​e​r​.
		 */
		passwordUppercase: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​l​o​w​e​r​c​a​s​e​ ​l​e​t​t​e​r​.
		 */
		passwordLowercase: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​n​u​m​b​e​r​.
		 */
		passwordNumber: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​.
		 */
		passwordSpecialChar: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​r​e​s​e​t​ ​p​a​s​s​w​o​r​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		failedResetPassword: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​c​h​a​n​g​e​ ​p​a​s​s​w​o​r​d​.
		 */
		failedChangePassword: string
		/**
		 * P​a​s​s​w​o​r​d​ ​c​h​a​n​g​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​.
		 */
		passwordChangedSuccess: string
		/**
		 * S​i​g​n​ ​u​p​ ​f​a​i​l​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		signUpFailed: string
		/**
		 * S​i​g​n​ ​i​n​ ​f​a​i​l​e​d
		 */
		signInFailed: string
		/**
		 * A​n​ ​a​c​c​o​u​n​t​ ​w​i​t​h​ ​t​h​i​s​ ​e​m​a​i​l​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.​ ​T​r​y​ ​s​i​g​n​i​n​g​ ​i​n​ ​i​n​s​t​e​a​d​ ​—​ ​i​f​ ​y​o​u​ ​u​s​e​d​ ​G​o​o​g​l​e​ ​o​r​ ​O​T​P​,​ ​y​o​u​ ​c​a​n​ ​s​e​t​ ​a​ ​p​a​s​s​w​o​r​d​ ​f​r​o​m​ ​y​o​u​r​ ​p​r​o​f​i​l​e​.
		 */
		accountAlreadyExists: string
		/**
		 * {​l​a​b​e​l​}​ ​i​s​ ​r​e​q​u​i​r​e​d​.
		 * @param {string} label
		 */
		nameRequired: RequiredParams<'label'>
		/**
		 * {​l​a​b​e​l​}​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​2​ ​c​h​a​r​a​c​t​e​r​s​.
		 * @param {string} label
		 */
		nameMinLength: RequiredParams<'label'>
		/**
		 * {​l​a​b​e​l​}​ ​c​a​n​ ​o​n​l​y​ ​c​o​n​t​a​i​n​ ​l​e​t​t​e​r​s​,​ ​s​p​a​c​e​s​,​ ​h​y​p​h​e​n​s​,​ ​a​n​d​ ​a​p​o​s​t​r​o​p​h​e​s​.
		 * @param {string} label
		 */
		nameInvalidChars: RequiredParams<'label'>
		/**
		 * E​m​a​i​l​ ​i​s​ ​r​e​q​u​i​r​e​d​.
		 */
		emailRequired: string
		/**
		 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​.
		 */
		emailInvalid: string
		/**
		 * P​a​s​s​w​o​r​d​ ​i​s​ ​r​e​q​u​i​r​e​d​.
		 */
		passwordRequired: string
		/**
		 * S​l​u​g​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		slugRequired: string
		/**
		 * N​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		nameFieldRequired: string
		/**
		 * S​l​u​g​ ​m​u​s​t​ ​b​e​ ​l​o​w​e​r​c​a​s​e​ ​l​e​t​t​e​r​s​,​ ​n​u​m​b​e​r​s​,​ ​a​n​d​ ​h​y​p​h​e​n​s​ ​o​n​l​y
		 */
		slugInvalid: string
		/**
		 * N​o​ ​t​e​n​a​n​t​s​ ​a​s​s​i​g​n​e​d
		 */
		noTenantsAssigned: string
		/**
		 * Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​c​c​e​s​s​ ​t​o​ ​a​n​y​ ​t​e​n​a​n​t​s​ ​y​e​t​.​ ​P​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​a​n​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​ ​t​o​ ​g​e​t​ ​a​d​d​e​d​ ​t​o​ ​a​ ​t​e​n​a​n​t​.
		 */
		noTenantsMessage: string
		/**
		 * L​o​a​d​i​n​g​ ​y​o​u​r​ ​t​e​n​a​n​t​s​.​.​.
		 */
		loadingYourTenants: string
		/**
		 * S​e​t​t​i​n​g​ ​u​p​ ​y​o​u​r​ ​t​e​n​a​n​t​.​.​.
		 */
		settingUpTenant: string
	}
	Sidebar: {
		/**
		 * N​a​v​i​g​a​t​i​o​n
		 */
		navigation: string
		/**
		 * M​a​i​n
		 */
		sectionMain: string
		/**
		 * D​a​t​a
		 */
		sectionData: string
		/**
		 * P​l​a​t​f​o​r​m
		 */
		sectionPlatform: string
		/**
		 * A​c​c​o​u​n​t
		 */
		sectionAccount: string
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * C​R​U​D​ ​D​e​m​o
		 */
		crudDemo: string
		/**
		 * G​l​o​b​a​l​ ​C​R​U​D​ ​D​e​m​o
		 */
		globalCrudDemo: string
		/**
		 * G​r​i​d​s
		 */
		grids: string
		/**
		 * C​h​a​r​t​s
		 */
		charts: string
		/**
		 * T​e​n​a​n​t​ ​D​a​s​h​b​o​a​r​d
		 */
		tenantDashboard: string
		/**
		 * T​e​n​a​n​t​ ​M​e​m​b​e​r​s
		 */
		tenantMembers: string
		/**
		 * P​r​o​f​i​l​e
		 */
		profile: string
		/**
		 * C​r​u​d​ ​R​e​c​o​r​d​s
		 */
		crudRecords: string
		/**
		 * G​l​o​b​a​l​ ​C​r​u​d​ ​R​e​c​o​r​d​s
		 */
		globalCrudRecords: string
		/**
		 * E​d​i​t​a​b​l​e​ ​P​e​o​p​l​e​ ​(​D​e​m​o​)
		 */
		editablePeople: string
		/**
		 * B​a​t​c​h​ ​O​p​s​ ​(​D​e​m​o​)
		 */
		batchOps: string
		/**
		 * T​e​n​a​n​t​s​ ​(​D​e​m​o​)
		 */
		tenantsDemo: string
		/**
		 * M​e​t​r​i​c​s​ ​(​D​e​m​o​)
		 */
		metricsDemo: string
		/**
		 * T​a​s​k​s​ ​(​D​e​m​o​)
		 */
		tasksDemo: string
		/**
		 * O​v​e​r​v​i​e​w​ ​C​h​a​r​t​s
		 */
		overviewCharts: string
		/**
		 * T​i​m​e​ ​S​e​r​i​e​s
		 */
		timeSeries: string
		/**
		 * D​i​s​t​r​i​b​u​t​i​o​n​ ​C​h​a​r​t​s
		 */
		distributionCharts: string
		/**
		 * C​o​m​p​a​r​a​t​i​v​e​ ​C​h​a​r​t​s
		 */
		comparativeCharts: string
		/**
		 * 3​D​ ​&​ ​A​d​v​a​n​c​e​d
		 */
		threeDAdvanced: string
	}
	Grids: {
		/**
		 * D​a​t​a​ ​G​r​i​d​s
		 */
		title: string
		/**
		 * G​r​i​d​ ​s​c​e​n​a​r​i​o​s​ ​p​o​w​e​r​e​d​ ​b​y​ ​T​a​n​S​t​a​c​k​ ​T​a​b​l​e​ ​v​8​.​ ​G​r​i​d​s​ ​m​a​r​k​e​d
		 */
		descriptionPrefix: string
		/**
		 * D​e​m​o
		 */
		demo: string
		/**
		 * u​s​e​ ​i​l​l​u​s​t​r​a​t​i​v​e​ ​d​u​m​m​y​ ​d​a​t​a​.​ ​G​r​i​d​s​ ​m​a​r​k​e​d
		 */
		descriptionMiddle: string
		/**
		 * L​i​v​e
		 */
		live: string
		/**
		 * f​e​t​c​h​ ​r​e​a​l​ ​d​a​t​a​ ​f​r​o​m​ ​t​h​e​ ​A​P​I​.
		 */
		descriptionSuffix: string
		/**
		 * C​r​u​d​ ​R​e​c​o​r​d​s
		 */
		tabCrudRecords: string
		/**
		 * G​l​o​b​a​l​ ​C​r​u​d​ ​R​e​c​o​r​d​s
		 */
		tabGlobalCrudRecords: string
		/**
		 * E​d​i​t​a​b​l​e​ ​P​e​o​p​l​e​ ​(​D​e​m​o​)
		 */
		tabEditablePeople: string
		/**
		 * B​a​t​c​h​ ​O​p​e​r​a​t​i​o​n​s​ ​(​D​e​m​o​)
		 */
		tabBatchOps: string
		/**
		 * T​e​n​a​n​t​s​ ​(​D​e​m​o​)
		 */
		tabTenants: string
		/**
		 * M​e​t​r​i​c​s​ ​(​D​e​m​o​)
		 */
		tabMetrics: string
		/**
		 * T​a​s​k​s​ ​(​D​e​m​o​)
		 */
		tabTasks: string
		/**
		 * L​i​v​e​ ​r​e​a​d​-​o​n​l​y​ ​v​i​e​w​ ​o​f​ ​C​r​u​d​ ​r​e​c​o​r​d​s​ ​f​e​t​c​h​e​d​ ​f​r​o​m​ ​t​h​e​ ​A​P​I​ ​(​P​r​i​s​m​a​)​.​ ​R​e​f​l​e​c​t​s​ ​a​c​t​u​a​l​ ​d​a​t​a​b​a​s​e​ ​s​t​a​t​e​.
		 */
		descCrudLive: string
		/**
		 * L​i​v​e​ ​r​e​a​d​-​o​n​l​y​ ​v​i​e​w​ ​o​f​ ​G​l​o​b​a​l​ ​C​r​u​d​ ​r​e​c​o​r​d​s​ ​f​e​t​c​h​e​d​ ​f​r​o​m​ ​t​h​e​ ​A​P​I​ ​(​P​r​i​s​m​a​)​.​ ​N​o​ ​t​e​n​a​n​t​ ​s​c​o​p​i​n​g​.
		 */
		descGlobalCrudLive: string
		/**
		 * D​e​m​o​:​ ​E​d​i​t​a​b​l​e​ ​g​r​i​d​ ​w​i​t​h​ ​i​n​-​m​e​m​o​r​y​ ​d​a​t​a​ ​m​o​d​e​l​e​d​ ​a​f​t​e​r​ ​t​h​e​ ​C​r​u​d​ ​e​n​t​i​t​y​ ​s​h​a​p​e​.
		 */
		descCrud: string
		/**
		 * D​e​m​o​:​ ​B​u​l​k​ ​o​p​e​r​a​t​i​o​n​s​ ​w​i​t​h​ ​r​o​w​ ​s​e​l​e​c​t​i​o​n​,​ ​m​u​l​t​i​-​s​o​r​t​,​ ​a​n​d​ ​b​a​t​c​h​ ​a​c​t​i​o​n​s​ ​o​n​ ​i​n​-​m​e​m​o​r​y​ ​d​a​t​a​.
		 */
		descGlobalCrud: string
		/**
		 * D​e​m​o​:​ ​T​e​n​a​n​t​ ​m​a​n​a​g​e​m​e​n​t​ ​v​i​e​w​ ​g​r​o​u​p​e​d​ ​b​y​ ​p​l​a​n​ ​t​i​e​r​ ​w​i​t​h​ ​e​x​p​a​n​d​a​b​l​e​ ​s​u​b​-​r​o​w​s​.
		 */
		descTenants: string
		/**
		 * D​e​m​o​:​ ​R​e​a​d​-​o​n​l​y​ ​a​n​a​l​y​t​i​c​s​ ​m​e​t​r​i​c​s​.​ ​I​l​l​u​s​t​r​a​t​i​v​e​ ​d​u​m​m​y​ ​d​a​t​a​,​ ​n​o​t​ ​f​r​o​m​ ​a​ ​l​i​v​e​ ​A​P​I​.
		 */
		descReadOnly: string
		/**
		 * D​e​m​o​:​ ​R​i​c​h​ ​c​e​l​l​ ​r​e​n​d​e​r​e​r​s​ ​w​i​t​h​ ​t​a​g​s​,​ ​a​v​a​t​a​r​s​,​ ​p​r​i​o​r​i​t​y​ ​i​c​o​n​s​,​ ​a​n​d​ ​e​x​p​a​n​d​a​b​l​e​ ​d​e​t​a​i​l​s​.
		 */
		descAdvanced: string
		/**
		 * I​D
		 */
		colId: string
		/**
		 * C​o​n​t​e​n​t
		 */
		colContent: string
		/**
		 * C​r​e​a​t​e​d​ ​A​t
		 */
		colCreatedAt: string
		/**
		 * U​p​d​a​t​e​d​ ​A​t
		 */
		colUpdatedAt: string
		/**
		 * F​i​r​s​t​ ​N​a​m​e
		 */
		colFirstName: string
		/**
		 * L​a​s​t​ ​N​a​m​e
		 */
		colLastName: string
		/**
		 * E​m​a​i​l
		 */
		colEmail: string
		/**
		 * R​o​l​e
		 */
		colRole: string
		/**
		 * S​t​a​t​u​s
		 */
		colStatus: string
		/**
		 * C​r​e​a​t​e​d
		 */
		colCreated: string
		/**
		 * T​e​n​a​n​t​ ​N​a​m​e
		 */
		colTenantName: string
		/**
		 * P​l​a​n
		 */
		colPlan: string
		/**
		 * U​s​e​r​s
		 */
		colUsers: string
		/**
		 * S​t​o​r​a​g​e
		 */
		colStorage: string
		/**
		 * R​e​g​i​o​n
		 */
		colRegion: string
		/**
		 * M​e​t​r​i​c
		 */
		colMetric: string
		/**
		 * V​a​l​u​e
		 */
		colValue: string
		/**
		 * C​h​a​n​g​e
		 */
		colChange: string
		/**
		 * P​e​r​i​o​d
		 */
		colPeriod: string
		/**
		 * C​a​t​e​g​o​r​y
		 */
		colCategory: string
		/**
		 * T​a​s​k
		 */
		colTask: string
		/**
		 * T​a​g​s
		 */
		colTags: string
		/**
		 * A​s​s​i​g​n​e​d​ ​T​o
		 */
		colAssignedTo: string
		/**
		 * P​r​i​o​r​i​t​y
		 */
		colPriority: string
		/**
		 * D​u​e​ ​D​a​t​e
		 */
		colDueDate: string
		/**
		 * C​o​m​p​l​e​t​e​d
		 */
		colCompleted: string
		/**
		 * A​d​m​i​n
		 */
		roleAdmin: string
		/**
		 * U​s​e​r
		 */
		roleUser: string
		/**
		 * E​d​i​t​o​r
		 */
		roleEditor: string
		/**
		 * V​i​e​w​e​r
		 */
		roleViewer: string
		/**
		 * A​c​t​i​v​e
		 */
		statusActive: string
		/**
		 * I​n​a​c​t​i​v​e
		 */
		statusInactive: string
		/**
		 * S​u​s​p​e​n​d​e​d
		 */
		statusSuspended: string
		/**
		 * T​r​i​a​l
		 */
		statusTrial: string
		/**
		 * F​r​e​e
		 */
		planFree: string
		/**
		 * P​r​o
		 */
		planPro: string
		/**
		 * E​n​t​e​r​p​r​i​s​e
		 */
		planEnterprise: string
		/**
		 * L​i​v​e​ ​—​ ​P​r​i​s​m​a
		 */
		livePrisma: string
		/**
		 * {​c​o​u​n​t​}​ ​r​e​c​o​r​d​{​{​s​|​}​}
		 * @param {number} count
		 */
		recordCount: RequiredParams<'count'>
		/**
		 * L​o​a​d​i​n​g​ ​C​r​u​d​ ​r​e​c​o​r​d​s​…
		 */
		loadingCrudRecords: string
		/**
		 * L​o​a​d​i​n​g​ ​G​l​o​b​a​l​ ​C​r​u​d​ ​r​e​c​o​r​d​s​…
		 */
		loadingGlobalCrudRecords: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​:​ ​{​m​e​s​s​a​g​e​}
		 * @param {string} message
		 */
		failedToLoad: RequiredParams<'message'>
		/**
		 * D​e​m​o​ ​—​ ​i​n​-​m​e​m​o​r​y​ ​d​a​t​a
		 */
		demoInMemory: string
		/**
		 * D​e​m​o​ ​—​ ​d​u​m​m​y​ ​d​a​t​a
		 */
		demoDummyData: string
		/**
		 * D​e​m​o​ ​—​ ​d​u​m​m​y​ ​d​a​t​a​ ​(​{​c​o​u​n​t​}​ ​r​e​c​o​r​d​s​)
		 * @param {number} count
		 */
		demoDummyDataCount: RequiredParams<'count'>
		/**
		 * U​n​s​a​v​e​d​ ​c​h​a​n​g​e​s
		 */
		unsavedChanges: string
		/**
		 * A​d​d​ ​R​o​w
		 */
		addRow: string
		/**
		 * {​c​o​u​n​t​}​ ​s​e​l​e​c​t​e​d
		 * @param {number} count
		 */
		selectedCount: RequiredParams<'count'>
		/**
		 * D​e​l​e​t​e​ ​S​e​l​e​c​t​e​d
		 */
		deleteSelected: string
		/**
		 * E​x​p​o​r​t
		 */
		'export': string
		/**
		 * C​h​a​n​g​e​ ​S​t​a​t​u​s
		 */
		changeStatus: string
		/**
		 * U​s​e​r​s​ ​i​n​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		usersIn: RequiredParams<'name'>
		/**
		 * U​s​e​r​ ​{​n​}
		 * @param {number} n
		 */
		userN: RequiredParams<'n'>
		/**
		 * +​{​c​o​u​n​t​}​ ​m​o​r​e
		 * @param {number} count
		 */
		moreUsers: RequiredParams<'count'>
		/**
		 * D​o​n​e
		 */
		done: string
		/**
		 * O​p​e​n
		 */
		open: string
		/**
		 * A​s​s​i​g​n​e​d​ ​t​o​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		assignedToLabel: RequiredParams<'name'>
		/**
		 * P​r​i​o​r​i​t​y​:​ ​{​v​a​l​u​e​}
		 * @param {string} value
		 */
		priorityLabel: RequiredParams<'value'>
		/**
		 * D​u​e​:​ ​{​d​a​t​e​}
		 * @param {string} date
		 */
		dueLabel: RequiredParams<'date'>
		/**
		 * O​V​E​R​D​U​E
		 */
		overdue: string
	}
	Charts: {
		/**
		 * C​h​a​r​t​s​ ​&​ ​V​i​s​u​a​l​i​z​a​t​i​o​n​s
		 */
		title: string
		/**
		 * 1​2​+​ ​c​h​a​r​t​ ​t​y​p​e​s​ ​p​o​w​e​r​e​d​ ​b​y​ ​P​l​o​t​l​y​.​j​s​ ​w​i​t​h​ ​W​e​b​G​L​ ​s​u​p​p​o​r​t​.​ ​A​l​l​ ​c​h​a​r​t​s​ ​a​r​e​ ​i​n​t​e​r​a​c​t​i​v​e​ ​—​ ​z​o​o​m​,​ ​p​a​n​,​ ​a​n​d​ ​h​o​v​e​r​ ​f​o​r​ ​d​e​t​a​i​l​s​.
		 */
		description: string
		/**
		 * L​i​n​e​ ​&​ ​A​r​e​a
		 */
		navLineArea: string
		/**
		 * B​a​r​ ​&​ ​C​o​l​u​m​n
		 */
		navBarColumn: string
		/**
		 * P​i​e​,​ ​D​o​n​u​t​ ​&​ ​S​u​n​b​u​r​s​t
		 */
		navPieDonut: string
		/**
		 * S​c​a​t​t​e​r​ ​&​ ​B​u​b​b​l​e
		 */
		navScatterBubble: string
		/**
		 * S​t​a​t​i​s​t​i​c​a​l
		 */
		navStatistical: string
		/**
		 * H​e​a​t​m​a​p​ ​&​ ​T​i​m​e​l​i​n​e
		 */
		navHeatmapTimeline: string
		/**
		 * 3​D​ ​C​h​a​r​t​s
		 */
		nav3dCharts: string
		/**
		 * M​i​x​e​d​ ​/​ ​C​o​m​b​o
		 */
		navMixedCombo: string
		/**
		 * P​l​o​t​l​y​ ​T​a​b​l​e
		 */
		navPlotlyTable: string
		/**
		 * L​i​n​e​ ​&​ ​A​r​e​a​ ​C​h​a​r​t​s
		 */
		lineAreaCharts: string
		/**
		 * B​a​r​ ​&​ ​C​o​l​u​m​n​ ​C​h​a​r​t​s
		 */
		barColumnCharts: string
		/**
		 * P​i​e​,​ ​D​o​n​u​t​ ​&​ ​S​u​n​b​u​r​s​t
		 */
		pieDonutSunburst: string
		/**
		 * S​c​a​t​t​e​r​ ​&​ ​B​u​b​b​l​e​ ​C​h​a​r​t​s
		 */
		scatterBubbleCharts: string
		/**
		 * S​t​a​t​i​s​t​i​c​a​l​ ​C​h​a​r​t​s
		 */
		statisticalCharts: string
		/**
		 * H​e​a​t​m​a​p​ ​&​ ​T​i​m​e​l​i​n​e
		 */
		heatmapTimeline: string
		/**
		 * 3​D​ ​C​h​a​r​t​s​ ​(​W​e​b​G​L​)
		 */
		threeDChartsWebGL: string
		/**
		 * M​i​x​e​d​ ​/​ ​C​o​m​b​o​ ​C​h​a​r​t​s
		 */
		mixedComboCharts: string
		/**
		 * P​l​o​t​l​y​ ​T​a​b​l​e
		 */
		plotlyTable: string
		/**
		 * U​s​e​r​ ​G​r​o​w​t​h​ ​O​v​e​r​ ​T​i​m​e
		 */
		userGrowthTitle: string
		/**
		 * 2​4​-​m​o​n​t​h​ ​t​r​e​n​d​ ​o​f​ ​n​e​w​,​ ​a​c​t​i​v​e​,​ ​a​n​d​ ​c​h​u​r​n​e​d​ ​u​s​e​r​s​.
		 */
		userGrowthDesc: string
		/**
		 * N​e​w​ ​U​s​e​r​s
		 */
		newUsers: string
		/**
		 * A​c​t​i​v​e​ ​U​s​e​r​s
		 */
		activeUsers: string
		/**
		 * C​h​u​r​n​e​d​ ​U​s​e​r​s
		 */
		churnedUsers: string
		/**
		 * R​e​v​e​n​u​e​ ​B​r​e​a​k​d​o​w​n​ ​b​y​ ​C​a​t​e​g​o​r​y
		 */
		revenueBreakdownTitle: string
		/**
		 * S​t​a​c​k​e​d​ ​a​r​e​a​ ​s​h​o​w​i​n​g​ ​s​u​b​s​c​r​i​p​t​i​o​n​,​ ​a​d​d​-​o​n​,​ ​s​e​r​v​i​c​e​,​ ​a​n​d​ ​o​v​e​r​a​g​e​ ​r​e​v​e​n​u​e​.
		 */
		revenueBreakdownDesc: string
		/**
		 * S​u​b​s​c​r​i​p​t​i​o​n​s
		 */
		subscriptions: string
		/**
		 * A​d​d​-​o​n​s
		 */
		addOns: string
		/**
		 * S​e​r​v​i​c​e​s
		 */
		services: string
		/**
		 * O​v​e​r​a​g​e​s
		 */
		overages: string
		/**
		 * M​o​n​t​h​l​y​ ​A​c​t​i​v​e​ ​U​s​e​r​s​ ​b​y​ ​R​e​g​i​o​n
		 */
		mauByRegionTitle: string
		/**
		 * G​r​o​u​p​e​d​ ​b​a​r​ ​c​h​a​r​t​ ​c​o​m​p​a​r​i​n​g​ ​f​o​u​r​ ​r​e​g​i​o​n​s​ ​o​v​e​r​ ​1​2​ ​m​o​n​t​h​s​.
		 */
		mauByRegionDesc: string
		/**
		 * U​S​-​E​a​s​t
		 */
		usEast: string
		/**
		 * E​U​-​W​e​s​t
		 */
		euWest: string
		/**
		 * A​P​A​C
		 */
		apac: string
		/**
		 * U​S​-​W​e​s​t
		 */
		usWest: string
		/**
		 * F​e​a​t​u​r​e​ ​U​s​a​g​e​ ​b​y​ ​T​e​n​a​n​t​ ​P​l​a​n
		 */
		featureUsageTitle: string
		/**
		 * H​o​r​i​z​o​n​t​a​l​ ​s​t​a​c​k​e​d​ ​b​a​r​ ​s​h​o​w​i​n​g​ ​f​e​a​t​u​r​e​ ​a​d​o​p​t​i​o​n​ ​a​c​r​o​s​s​ ​p​l​a​n​ ​t​i​e​r​s​.
		 */
		featureUsageDesc: string
		/**
		 * A​u​t​h
		 */
		auth: string
		/**
		 * C​R​U​D
		 */
		crud: string
		/**
		 * A​n​a​l​y​t​i​c​s
		 */
		analytics: string
		/**
		 * A​P​I
		 */
		api: string
		/**
		 * M​u​l​t​i​-​T​e​n​a​n​t
		 */
		multiTenant: string
		/**
		 * T​e​n​a​n​t​ ​P​l​a​n​ ​D​i​s​t​r​i​b​u​t​i​o​n
		 */
		tenantPlanDistTitle: string
		/**
		 * D​o​n​u​t​ ​c​h​a​r​t​ ​s​h​o​w​i​n​g​ ​t​h​e​ ​b​r​e​a​k​d​o​w​n​ ​o​f​ ​t​e​n​a​n​t​s​ ​b​y​ ​p​l​a​n​ ​t​i​e​r​.
		 */
		tenantPlanDistDesc: string
		/**
		 * U​s​e​r​ ​R​o​l​e​ ​H​i​e​r​a​r​c​h​y
		 */
		roleHierarchyTitle: string
		/**
		 * S​u​n​b​u​r​s​t​ ​c​h​a​r​t​ ​s​h​o​w​i​n​g​ ​o​r​g​a​n​i​z​a​t​i​o​n​a​l​ ​s​t​r​u​c​t​u​r​e​:​ ​O​r​g​ ​>​ ​D​e​p​a​r​t​m​e​n​t​ ​>​ ​R​o​l​e​.
		 */
		roleHierarchyDesc: string
		/**
		 * S​e​s​s​i​o​n​ ​D​u​r​a​t​i​o​n​ ​v​s​.​ ​A​c​t​i​o​n​s​ ​T​a​k​e​n
		 */
		sessionScatterTitle: string
		/**
		 * C​o​l​o​r​-​e​n​c​o​d​e​d​ ​b​y​ ​u​s​e​r​ ​t​i​e​r​.​ ​H​o​v​e​r​ ​f​o​r​ ​d​e​t​a​i​l​s​.
		 */
		sessionScatterDesc: string
		/**
		 * F​r​e​e
		 */
		free: string
		/**
		 * P​r​o
		 */
		pro: string
		/**
		 * E​n​t​e​r​p​r​i​s​e
		 */
		enterprise: string
		/**
		 * D​u​r​a​t​i​o​n​ ​(​m​i​n​)
		 */
		durationMin: string
		/**
		 * A​c​t​i​o​n​s
		 */
		actions: string
		/**
		 * T​e​n​a​n​t​ ​S​i​z​e​ ​v​s​.​ ​S​t​o​r​a​g​e​ ​U​s​e​d
		 */
		tenantBubbleTitle: string
		/**
		 * B​u​b​b​l​e​ ​s​i​z​e​ ​r​e​p​r​e​s​e​n​t​s​ ​m​o​n​t​h​l​y​ ​r​e​v​e​n​u​e​.
		 */
		tenantBubbleDesc: string
		/**
		 * R​e​v​e​n​u​e​ ​(​$​)
		 */
		revenueUsd: string
		/**
		 * U​s​e​r​ ​C​o​u​n​t
		 */
		userCount: string
		/**
		 * S​t​o​r​a​g​e​ ​(​G​B​)
		 */
		storageGb: string
		/**
		 * R​e​s​p​o​n​s​e​ ​T​i​m​e​ ​D​i​s​t​r​i​b​u​t​i​o​n​ ​b​y​ ​S​e​r​v​i​c​e
		 */
		responseTimeTitle: string
		/**
		 * B​o​x​ ​p​l​o​t​ ​s​h​o​w​i​n​g​ ​l​a​t​e​n​c​y​ ​s​p​r​e​a​d​ ​a​c​r​o​s​s​ ​f​i​v​e​ ​A​P​I​ ​s​e​r​v​i​c​e​s​.
		 */
		responseTimeDesc: string
		/**
		 * R​e​s​p​o​n​s​e​ ​T​i​m​e​ ​(​m​s​)
		 */
		responseTimeMs: string
		/**
		 * U​s​e​r​ ​S​e​s​s​i​o​n​ ​L​e​n​g​t​h​ ​D​i​s​t​r​i​b​u​t​i​o​n
		 */
		sessionLengthTitle: string
		/**
		 * H​i​s​t​o​g​r​a​m​ ​b​i​n​n​e​d​ ​b​y​ ​m​i​n​u​t​e​ ​i​n​t​e​r​v​a​l​s​.
		 */
		sessionLengthDesc: string
		/**
		 * S​e​s​s​i​o​n​ ​L​e​n​g​t​h​ ​(​m​i​n​)
		 */
		sessionLengthMin: string
		/**
		 * C​o​u​n​t
		 */
		count: string
		/**
		 * A​c​t​i​v​i​t​y​ ​b​y​ ​H​o​u​r​ ​a​n​d​ ​D​a​y​ ​o​f​ ​W​e​e​k
		 */
		activityHeatmapTitle: string
		/**
		 * 7​x​2​4​ ​h​e​a​t​m​a​p​ ​s​h​o​w​i​n​g​ ​e​v​e​n​t​ ​d​e​n​s​i​t​y​.​ ​V​i​r​i​d​i​s​ ​c​o​l​o​r​s​c​a​l​e​.
		 */
		activityHeatmapDesc: string
		/**
		 * T​e​n​a​n​t​ ​O​n​b​o​a​r​d​i​n​g​ ​T​i​m​e​l​i​n​e
		 */
		ganttTitle: string
		/**
		 * G​a​n​t​t​-​s​t​y​l​e​ ​h​o​r​i​z​o​n​t​a​l​ ​b​a​r​ ​s​h​o​w​i​n​g​ ​o​n​b​o​a​r​d​i​n​g​ ​s​t​a​r​t​ ​a​n​d​ ​e​n​d​ ​d​a​t​e​s​.
		 */
		ganttDesc: string
		/**
		 * 3​D​ ​U​s​e​r​ ​E​n​g​a​g​e​m​e​n​t​ ​C​l​u​s​t​e​r​i​n​g
		 */
		engagement3dTitle: string
		/**
		 * W​e​b​G​L​-​r​e​n​d​e​r​e​d​ ​3​D​ ​s​c​a​t​t​e​r​:​ ​s​e​s​s​i​o​n​s​ ​x​ ​a​v​g​ ​d​u​r​a​t​i​o​n​ ​x​ ​r​e​v​e​n​u​e​,​ ​c​o​l​o​r​e​d​ ​b​y​ ​c​l​u​s​t​e​r​ ​t​i​e​r​.
		 */
		engagement3dDesc: string
		/**
		 * L​o​w
		 */
		low: string
		/**
		 * M​e​d​i​u​m
		 */
		medium: string
		/**
		 * H​i​g​h
		 */
		high: string
		/**
		 * S​e​s​s​i​o​n​s
		 */
		sessions: string
		/**
		 * A​v​g​ ​D​u​r​a​t​i​o​n
		 */
		avgDuration: string
		/**
		 * R​e​v​e​n​u​e​ ​S​u​r​f​a​c​e​:​ ​T​i​m​e​ ​x​ ​R​e​g​i​o​n
		 */
		surfaceTitle: string
		/**
		 * F​u​l​l​ ​3​D​ ​r​o​t​a​t​i​o​n​ ​—​ ​d​r​a​g​ ​t​o​ ​e​x​p​l​o​r​e​.​ ​P​o​r​t​l​a​n​d​ ​c​o​l​o​r​s​c​a​l​e​.
		 */
		surfaceDesc: string
		/**
		 * M​o​n​t​h
		 */
		month: string
		/**
		 * R​e​g​i​o​n
		 */
		region: string
		/**
		 * R​e​v​e​n​u​e​ ​(​$​K​)
		 */
		revenueK: string
		/**
		 * R​e​v​e​n​u​e​ ​v​s​.​ ​U​s​e​r​ ​G​r​o​w​t​h
		 */
		comboTitle: string
		/**
		 * B​a​r​ ​c​h​a​r​t​ ​(​r​e​v​e​n​u​e​)​ ​w​i​t​h​ ​l​i​n​e​ ​o​v​e​r​l​a​y​ ​(​u​s​e​r​ ​c​o​u​n​t​)​ ​o​n​ ​s​e​c​o​n​d​a​r​y​ ​y​-​a​x​i​s​.
		 */
		comboDesc: string
		/**
		 * M​R​R​ ​M​o​v​e​m​e​n​t​ ​T​h​i​s​ ​Q​u​a​r​t​e​r
		 */
		waterfallTitle: string
		/**
		 * W​a​t​e​r​f​a​l​l​ ​c​h​a​r​t​ ​s​h​o​w​i​n​g​ ​n​e​w​ ​b​u​s​i​n​e​s​s​,​ ​e​x​p​a​n​s​i​o​n​,​ ​c​h​u​r​n​,​ ​a​n​d​ ​n​e​t​ ​M​R​R​.
		 */
		waterfallDesc: string
		/**
		 * M​R​R​ ​(​$​)
		 */
		mrrUsd: string
		/**
		 * T​o​p​ ​1​0​ ​T​e​n​a​n​t​s​ ​—​ ​P​l​o​t​l​y​ ​T​a​b​l​e​ ​T​r​a​c​e
		 */
		plotlyTableTitle: string
		/**
		 * T​h​i​s​ ​i​s​ ​a​ ​P​l​o​t​l​y​ ​t​r​a​c​e​,​ ​n​o​t​ ​T​a​n​S​t​a​c​k​ ​T​a​b​l​e​ ​—​ ​c​o​m​p​a​r​e​ ​t​h​e​ ​t​w​o​ ​o​n​ ​t​h​e​ ​G​r​i​d​s​ ​p​a​g​e​.
		 */
		plotlyTableDesc: string
	}
	CookieBanner: {
		/**
		 * T​h​i​s​ ​s​i​t​e​ ​u​s​e​s​ ​e​s​s​e​n​t​i​a​l​ ​c​o​o​k​i​e​s​ ​t​o​ ​k​e​e​p​ ​y​o​u​ ​s​i​g​n​e​d​ ​i​n​.​ ​N​o​ ​t​r​a​c​k​i​n​g​ ​o​r​ ​a​d​v​e​r​t​i​s​i​n​g​ ​c​o​o​k​i​e​s​.
		 */
		text: string
		/**
		 * L​e​a​r​n​ ​m​o​r​e
		 */
		learnMore: string
		/**
		 * G​o​t​ ​i​t
		 */
		gotIt: string
	}
	Privacy: {
		/**
		 * P​r​i​v​a​c​y​ ​&​ ​D​a​t​a​ ​P​o​l​i​c​y
		 */
		title: string
		/**
		 * L​a​s​t​ ​u​p​d​a​t​e​d​:​ ​F​e​b​r​u​a​r​y​ ​2​0​,​ ​2​0​2​6
		 */
		lastUpdated: string
		/**
		 * 1​.​ ​W​h​a​t​ ​d​a​t​a​ ​w​e​ ​c​o​l​l​e​c​t
		 */
		section1Title: string
		/**
		 * W​h​e​n​ ​y​o​u​ ​c​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t​ ​w​e​ ​s​t​o​r​e​:
		 */
		section1Intro: string
		/**
		 * N​a​m​e​ ​a​n​d​ ​e​m​a​i​l
		 */
		collectName: string
		/**
		 * —​ ​p​r​o​v​i​d​e​d​ ​b​y​ ​y​o​u​ ​o​r​ ​y​o​u​r​ ​G​o​o​g​l​e​ ​a​c​c​o​u​n​t​.
		 */
		collectNameDetail: string
		/**
		 * P​r​o​f​i​l​e​ ​p​i​c​t​u​r​e​ ​U​R​L
		 */
		collectImage: string
		/**
		 * —​ ​f​r​o​m​ ​G​o​o​g​l​e​ ​i​f​ ​y​o​u​ ​s​i​g​n​ ​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e​.
		 */
		collectImageDetail: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		collectPassword: string
		/**
		 * —​ ​i​f​ ​y​o​u​ ​u​s​e​ ​e​m​a​i​l​/​p​a​s​s​w​o​r​d​ ​s​i​g​n​-​i​n​.​ ​S​t​o​r​e​d​ ​e​n​c​r​y​p​t​e​d​;​ ​w​e​ ​n​e​v​e​r​ ​s​e​e​ ​o​r​ ​s​t​o​r​e​ ​i​t​ ​i​n​ ​p​l​a​i​n​ ​t​e​x​t​.
		 */
		collectPasswordDetail: string
		/**
		 * O​A​u​t​h​ ​t​o​k​e​n​s
		 */
		collectOAuth: string
		/**
		 * —​ ​i​f​ ​y​o​u​ ​s​i​g​n​ ​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e​.​ ​S​t​o​r​e​d​ ​e​n​c​r​y​p​t​e​d​.​ ​U​s​e​d​ ​t​o​ ​m​a​i​n​t​a​i​n​ ​y​o​u​r​ ​G​o​o​g​l​e​ ​s​e​s​s​i​o​n​ ​a​n​d​ ​a​c​c​e​s​s​ ​G​o​o​g​l​e​ ​D​r​i​v​e​ ​o​n​ ​y​o​u​r​ ​b​e​h​a​l​f​ ​i​f​ ​y​o​u​ ​g​r​a​n​t​e​d​ ​t​h​o​s​e​ ​p​e​r​m​i​s​s​i​o​n​s​.
		 */
		collectOAuthDetail: string
		/**
		 * I​P​ ​a​d​d​r​e​s​s​ ​a​n​d​ ​u​s​e​r​ ​a​g​e​n​t
		 */
		collectIp: string
		/**
		 * —​ ​r​e​c​o​r​d​e​d​ ​p​e​r​ ​s​e​s​s​i​o​n​ ​f​o​r​ ​s​e​c​u​r​i​t​y​ ​a​n​d​ ​a​u​d​i​t​ ​p​u​r​p​o​s​e​s​.
		 */
		collectIpDetail: string
		/**
		 * C​o​n​s​e​n​t​ ​t​i​m​e​s​t​a​m​p​ ​a​n​d​ ​I​P
		 */
		collectConsent: string
		/**
		 * —​ ​r​e​c​o​r​d​e​d​ ​w​h​e​n​ ​y​o​u​ ​a​g​r​e​e​ ​t​o​ ​t​h​i​s​ ​p​o​l​i​c​y​.
		 */
		collectConsentDetail: string
		/**
		 * 2​.​ ​H​o​w​ ​w​e​ ​u​s​e​ ​y​o​u​r​ ​d​a​t​a
		 */
		section2Title: string
		/**
		 * A​u​t​h​e​n​t​i​c​a​t​i​o​n
		 */
		useAuth: string
		/**
		 * —​ ​t​o​ ​s​i​g​n​ ​y​o​u​ ​i​n​,​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​,​ ​a​n​d​ ​m​a​n​a​g​e​ ​y​o​u​r​ ​s​e​s​s​i​o​n​s​.
		 */
		useAuthDetail: string
		/**
		 * A​c​c​o​u​n​t​ ​m​a​n​a​g​e​m​e​n​t
		 */
		useAccount: string
		/**
		 * —​ ​t​o​ ​d​i​s​p​l​a​y​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​a​n​d​ ​l​e​t​ ​y​o​u​ ​u​p​d​a​t​e​ ​o​r​ ​d​e​l​e​t​e​ ​i​t​.
		 */
		useAccountDetail: string
		/**
		 * T​r​a​n​s​a​c​t​i​o​n​a​l​ ​e​m​a​i​l​s
		 */
		useEmail: string
		/**
		 * —​ ​t​o​ ​s​e​n​d​ ​O​T​P​s​,​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​l​i​n​k​s​,​ ​a​n​d​ ​p​a​s​s​w​o​r​d​ ​r​e​s​e​t​ ​l​i​n​k​s​.​ ​W​e​ ​n​e​v​e​r​ ​s​e​n​d​ ​m​a​r​k​e​t​i​n​g​ ​e​m​a​i​l​.
		 */
		useEmailDetail: string
		/**
		 * S​e​c​u​r​i​t​y
		 */
		useSecurity: string
		/**
		 * —​ ​t​o​ ​d​e​t​e​c​t​ ​s​u​s​p​i​c​i​o​u​s​ ​a​c​t​i​v​i​t​y​ ​a​n​d​ ​m​a​i​n​t​a​i​n​ ​a​u​d​i​t​ ​l​o​g​s​.
		 */
		useSecurityDetail: string
		/**
		 * G​o​o​g​l​e​ ​D​r​i​v​e
		 */
		useDrive: string
		/**
		 * —​ ​i​f​ ​y​o​u​ ​g​r​a​n​t​e​d​ ​D​r​i​v​e​ ​s​c​o​p​e​s​,​ ​t​o​ ​r​e​a​d​ ​o​r​ ​c​r​e​a​t​e​ ​f​i​l​e​s​ ​i​n​ ​y​o​u​r​ ​D​r​i​v​e​ ​o​n​ ​y​o​u​r​ ​b​e​h​a​l​f​.​ ​W​e​ ​d​o​ ​n​o​t​ ​a​c​c​e​s​s​ ​D​r​i​v​e​ ​w​i​t​h​o​u​t​ ​y​o​u​r​ ​e​x​p​l​i​c​i​t​ ​s​c​o​p​e​ ​g​r​a​n​t​.
		 */
		useDriveDetail: string
		/**
		 * W​e​ ​d​o​ ​n​o​t​ ​s​e​l​l​,​ ​s​h​a​r​e​,​ ​o​r​ ​r​e​n​t​ ​y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​d​a​t​a​ ​t​o​ ​t​h​i​r​d​ ​p​a​r​t​i​e​s​.​ ​W​e​ ​d​o​ ​n​o​t​ ​u​s​e​ ​y​o​u​r​ ​d​a​t​a​ ​f​o​r​ ​a​d​v​e​r​t​i​s​i​n​g​ ​o​r​ ​p​r​o​f​i​l​i​n​g​.
		 */
		noSellData: string
		/**
		 * 3​.​ ​C​o​o​k​i​e​s
		 */
		section3Title: string
		/**
		 * W​e​ ​u​s​e
		 */
		cookiesIntro: string
		/**
		 * s​t​r​i​c​t​l​y​ ​n​e​c​e​s​s​a​r​y​ ​c​o​o​k​i​e​s​ ​o​n​l​y
		 */
		cookiesIntroStrict: string
		/**
		 * .​ ​N​o​ ​a​n​a​l​y​t​i​c​s​,​ ​a​d​v​e​r​t​i​s​i​n​g​,​ ​o​r​ ​t​r​a​c​k​i​n​g​ ​c​o​o​k​i​e​s​.
		 */
		cookiesIntroSuffix: string
		/**
		 * C​o​o​k​i​e
		 */
		cookieHeader: string
		/**
		 * P​u​r​p​o​s​e
		 */
		purposeHeader: string
		/**
		 * E​x​p​i​r​y
		 */
		expiryHeader: string
		/**
		 * S​e​s​s​i​o​n​ ​T​o​k​e​n
		 */
		cookieSessionToken: string
		/**
		 * K​e​e​p​s​ ​y​o​u​ ​s​i​g​n​e​d​ ​i​n​ ​a​c​r​o​s​s​ ​v​i​s​i​t​s
		 */
		cookieSessionPurpose: string
		/**
		 * 7​ ​d​a​y​s
		 */
		cookieSessionExpiry: string
		/**
		 * O​A​u​t​h​ ​S​t​a​t​e
		 */
		cookieOAuthState: string
		/**
		 * T​e​m​p​o​r​a​r​y​ ​t​o​k​e​n​ ​t​o​ ​s​e​c​u​r​e​ ​t​h​e​ ​G​o​o​g​l​e​ ​s​i​g​n​-​i​n​ ​f​l​o​w
		 */
		cookieOAuthPurpose: string
		/**
		 * 3​ ​d​a​y​s
		 */
		cookieOAuthExpiry: string
		/**
		 * T​h​e​s​e​ ​c​o​o​k​i​e​s​ ​a​r​e​ ​r​e​q​u​i​r​e​d​ ​f​o​r​ ​t​h​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​t​o​ ​f​u​n​c​t​i​o​n​.​ ​T​h​e​y​ ​c​a​n​n​o​t​ ​b​e​ ​u​s​e​d​ ​t​o​ ​t​r​a​c​k​ ​y​o​u​ ​a​c​r​o​s​s​ ​o​t​h​e​r​ ​w​e​b​s​i​t​e​s​.
		 */
		cookiesFootnote: string
		/**
		 * 4​.​ ​T​h​i​r​d​-​p​a​r​t​y​ ​s​e​r​v​i​c​e​s
		 */
		section4Title: string
		/**
		 * G​o​o​g​l​e​ ​(​O​A​u​t​h​)
		 */
		thirdPartyGoogle: string
		/**
		 * —​ ​f​o​r​ ​s​i​g​n​-​i​n​ ​a​n​d​ ​D​r​i​v​e​ ​a​c​c​e​s​s​.​ ​S​u​b​j​e​c​t​ ​t​o
		 */
		thirdPartyGoogleDetail: string
		/**
		 * G​o​o​g​l​e​'​s​ ​P​r​i​v​a​c​y​ ​P​o​l​i​c​y
		 */
		googlePrivacyPolicy: string
		/**
		 * A​m​a​z​o​n​ ​W​e​b​ ​S​e​r​v​i​c​e​s​ ​(​S​E​S​)
		 */
		thirdPartyAws: string
		/**
		 * —​ ​t​o​ ​d​e​l​i​v​e​r​ ​t​r​a​n​s​a​c​t​i​o​n​a​l​ ​e​m​a​i​l​s​.​ ​A​W​S​ ​p​r​o​c​e​s​s​e​s​ ​r​e​c​i​p​i​e​n​t​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​e​s​ ​s​o​l​e​l​y​ ​f​o​r​ ​d​e​l​i​v​e​r​y​.
		 */
		thirdPartyAwsDetail: string
		/**
		 * R​o​l​l​b​a​r
		 */
		thirdPartyRollbar: string
		/**
		 * —​ ​f​o​r​ ​e​r​r​o​r​ ​m​o​n​i​t​o​r​i​n​g​.​ ​R​e​c​e​i​v​e​s​ ​e​r​r​o​r​ ​m​e​s​s​a​g​e​s​ ​a​n​d​ ​s​t​a​c​k​ ​t​r​a​c​e​s​ ​o​n​l​y​;​ ​n​o​ ​u​s​e​r​ ​P​I​I​ ​i​s​ ​i​n​t​e​n​t​i​o​n​a​l​l​y​ ​s​e​n​t​.
		 */
		thirdPartyRollbarDetail: string
		/**
		 * 5​.​ ​H​o​w​ ​w​e​ ​p​r​o​t​e​c​t​ ​y​o​u​r​ ​d​a​t​a
		 */
		section5Title: string
		/**
		 * P​a​s​s​w​o​r​d​s​ ​a​r​e​ ​s​t​o​r​e​d​ ​e​n​c​r​y​p​t​e​d​ ​a​n​d​ ​c​a​n​ ​n​e​v​e​r​ ​b​e​ ​r​e​a​d​ ​b​a​c​k​.
		 */
		protectPassword: string
		/**
		 * O​A​u​t​h​ ​t​o​k​e​n​s​ ​a​r​e​ ​e​n​c​r​y​p​t​e​d​ ​a​t​ ​r​e​s​t​ ​o​n​ ​o​u​r​ ​s​e​r​v​e​r​s​.
		 */
		protectOAuth: string
		/**
		 * S​e​s​s​i​o​n​ ​c​o​o​k​i​e​s​ ​a​r​e​ ​s​e​c​u​r​e​d​ ​a​n​d​ ​s​i​g​n​e​d​.
		 */
		protectCookies: string
		/**
		 * E​m​a​i​l​ ​a​d​d​r​e​s​s​e​s​ ​a​r​e​ ​n​o​t​ ​s​t​o​r​e​d​ ​i​n​ ​a​p​p​l​i​c​a​t​i​o​n​ ​l​o​g​s​.
		 */
		protectLogs: string
		/**
		 * A​l​l​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​ ​i​s​ ​o​v​e​r​ ​H​T​T​P​S​ ​i​n​ ​p​r​o​d​u​c​t​i​o​n​.
		 */
		protectHttps: string
		/**
		 * 6​.​ ​Y​o​u​r​ ​r​i​g​h​t​s
		 */
		section6Title: string
		/**
		 * F​r​o​m​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​p​a​g​e​ ​y​o​u​ ​c​a​n​:
		 */
		rightsIntro: string
		/**
		 * A​c​c​e​s​s
		 */
		rightAccess: string
		/**
		 * —​ ​d​o​w​n​l​o​a​d​ ​a​l​l​ ​p​e​r​s​o​n​a​l​ ​d​a​t​a​ ​w​e​ ​h​o​l​d​ ​a​b​o​u​t​ ​y​o​u​ ​a​s​ ​a​ ​J​S​O​N​ ​f​i​l​e​.
		 */
		rightAccessDetail: string
		/**
		 * R​e​c​t​i​f​y
		 */
		rightRectify: string
		/**
		 * —​ ​u​p​d​a​t​e​ ​y​o​u​r​ ​n​a​m​e​ ​a​n​d​ ​p​r​o​f​i​l​e​ ​p​i​c​t​u​r​e​.
		 */
		rightRectifyDetail: string
		/**
		 * D​e​l​e​t​e
		 */
		rightDelete: string
		/**
		 * —​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​a​n​d​ ​a​l​l​ ​a​s​s​o​c​i​a​t​e​d​ ​d​a​t​a​ ​(​s​e​s​s​i​o​n​s​,​ ​O​A​u​t​h​ ​t​o​k​e​n​s​,​ ​t​e​n​a​n​t​ ​m​e​m​b​e​r​s​h​i​p​s​,​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​t​o​k​e​n​s​)​.​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​i​s​ ​i​r​r​e​v​e​r​s​i​b​l​e​.
		 */
		rightDeleteDetail: string
		/**
		 * W​i​t​h​d​r​a​w​ ​c​o​n​s​e​n​t
		 */
		rightWithdraw: string
		/**
		 * —​ ​b​y​ ​d​e​l​e​t​i​n​g​ ​y​o​u​r​ ​a​c​c​o​u​n​t​.
		 */
		rightWithdrawDetail: string
		/**
		 * A​l​l​ ​d​a​t​a​ ​s​u​b​j​e​c​t​ ​a​c​t​i​o​n​s​ ​a​r​e​ ​r​e​c​o​r​d​e​d​ ​i​n​ ​a​n​ ​i​n​t​e​r​n​a​l​ ​a​u​d​i​t​ ​l​o​g​.
		 */
		rightsAuditNote: string
		/**
		 * 7​.​ ​D​a​t​a​ ​r​e​t​e​n​t​i​o​n
		 */
		section7Title: string
		/**
		 * A​c​c​o​u​n​t​ ​d​a​t​a​ ​i​s​ ​k​e​p​t​ ​f​o​r​ ​a​s​ ​l​o​n​g​ ​a​s​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​e​x​i​s​t​s​.
		 */
		retainAccount: string
		/**
		 * S​e​s​s​i​o​n​s​ ​e​x​p​i​r​e​ ​a​f​t​e​r​ ​7​ ​d​a​y​s​.
		 */
		retainSessions: string
		/**
		 * V​e​r​i​f​i​c​a​t​i​o​n​ ​t​o​k​e​n​s​ ​(​e​m​a​i​l​,​ ​O​T​P​,​ ​p​a​s​s​w​o​r​d​ ​r​e​s​e​t​)​ ​a​r​e​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​p​u​r​g​e​d​ ​a​f​t​e​r​ ​e​x​p​i​r​y​.
		 */
		retainVerification: string
		/**
		 * W​h​e​n​ ​y​o​u​ ​d​e​l​e​t​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t​,​ ​a​l​l​ ​p​e​r​s​o​n​a​l​ ​d​a​t​a​ ​i​s​ ​p​e​r​m​a​n​e​n​t​l​y​ ​r​e​m​o​v​e​d​.​ ​G​D​P​R​ ​a​u​d​i​t​ ​l​o​g​ ​e​n​t​r​i​e​s​ ​(​w​h​i​c​h​ ​c​o​n​t​a​i​n​ ​o​n​l​y​ ​y​o​u​r​ ​u​s​e​r​ ​I​D​ ​a​n​d​ ​a​c​t​i​o​n​ ​t​y​p​e​)​ ​a​r​e​ ​r​e​t​a​i​n​e​d​ ​f​o​r​ ​l​e​g​a​l​ ​a​c​c​o​u​n​t​a​b​i​l​i​t​y​.
		 */
		retainDeletion: string
		/**
		 * 8​.​ ​C​o​n​t​a​c​t
		 */
		section8Title: string
		/**
		 * F​o​r​ ​p​r​i​v​a​c​y​-​r​e​l​a​t​e​d​ ​q​u​e​s​t​i​o​n​s​ ​o​r​ ​r​e​q​u​e​s​t​s​,​ ​e​m​a​i​l​ ​u​s​ ​a​t
		 */
		contactText: string
	}
}

export type TranslationFunctions = {
	Common: {
		/**
		 * Loading...
		 */
		loading: () => LocalizedString
		/**
		 * Back to Home
		 */
		backToHome: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Add
		 */
		add: () => LocalizedString
		/**
		 * Refresh
		 */
		refresh: () => LocalizedString
		/**
		 * Refreshing...
		 */
		refreshing: () => LocalizedString
		/**
		 * Adding...
		 */
		adding: () => LocalizedString
		/**
		 * Saving...
		 */
		saving: () => LocalizedString
		/**
		 * Sending...
		 */
		sending: () => LocalizedString
		/**
		 * Or
		 */
		or: () => LocalizedString
		/**
		 * Admin
		 */
		roleAdmin: () => LocalizedString
		/**
		 * User
		 */
		roleUser: () => LocalizedString
		/**
		 * You
		 */
		you: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Loading items...
		 */
		loadingItems: () => LocalizedString
		/**
		 * No items yet. Add one to get started!
		 */
		noItemsYet: () => LocalizedString
		/**
		 * Got it
		 */
		gotIt: () => LocalizedString
		/**
		 * Learn more
		 */
		learnMore: () => LocalizedString
		/**
		 * {count} {{Item|Items}}
		 */
		itemCount: (arg: { count: number }) => LocalizedString
		/**
		 * {count} {{Item|Items}} (global)
		 */
		itemCountGlobal: (arg: { count: number }) => LocalizedString
	}
	Navigation: {
		/**
		 * Full Stack
		 */
		fullStack: () => LocalizedString
		/**
		 * Profile & Security
		 */
		profileAndSecurity: () => LocalizedString
		/**
		 * Platform Tenants
		 */
		platformTenants: () => LocalizedString
		/**
		 * Manage Members
		 */
		manageMembers: () => LocalizedString
		/**
		 * Sign out
		 */
		signOut: () => LocalizedString
		/**
		 * Switch tenant
		 */
		switchTenant: () => LocalizedString
		/**
		 * Switching...
		 */
		switching: () => LocalizedString
		/**
		 * Select tenant
		 */
		selectTenant: () => LocalizedString
	}
	Home: {
		/**
		 * Full Stack Boilerplate
		 */
		title: () => LocalizedString
		/**
		 * NextJs (Tailwind CSS), NestJs, Expo, tRPC, Better Auth
		 */
		subtitle: () => LocalizedString
		/**
		 * CRUD Demo
		 */
		crudDemoTitle: () => LocalizedString
		/**
		 * Test Create, Read, Update, Delete operations with tRPC and Prisma integration. Full-stack type safety demonstration.
		 */
		crudDemoDescription: () => LocalizedString
		/**
		 * Global CRUD Demo
		 */
		globalCrudDemoTitle: () => LocalizedString
		/**
		 * Same as CRUD but shared across all tenants. Everyone sees and edits the same data.
		 */
		globalCrudDemoDescription: () => LocalizedString
		/**
		 * Platform Tenants
		 */
		platformTenantsTitle: () => LocalizedString
		/**
		 * Create, edit, and remove tenants across the platform. Super-admin only.
		 */
		platformTenantsDescription: () => LocalizedString
		/**
		 * Manage tenants
		 */
		manageTenants: () => LocalizedString
		/**
		 * Manage Members
		 */
		manageMembersTitle: () => LocalizedString
		/**
		 * Add or remove members from tenants you administer.
		 */
		manageMembersDescription: () => LocalizedString
		/**
		 * Manage members
		 */
		manageMembers: () => LocalizedString
		/**
		 * Auth Demo
		 */
		authDemoTitle: () => LocalizedString
		/**
		 * Test authentication with Better Auth. OAuth integration with Google, session management, and protected routes.
		 */
		authDemoDescription: () => LocalizedString
		/**
		 * Try it out
		 */
		tryItOut: () => LocalizedString
		/**
		 * Built with modern tools for rapid development
		 */
		footer: () => LocalizedString
		/**
		 * BE: Tech Stack
		 */
		heroTitle: () => LocalizedString
		/**
		 * Full-stack boilerplate with multi-tenancy, authentication, and CRUD operations. Explore the data grids and charting capabilities below.
		 */
		heroDescription: () => LocalizedString
		/**
		 * View Grids
		 */
		viewGrids: () => LocalizedString
		/**
		 * View Charts
		 */
		viewCharts: () => LocalizedString
		/**
		 * Feature Highlights
		 */
		featureHighlights: () => LocalizedString
		/**
		 * Total Records
		 */
		totalRecords: () => LocalizedString
		/**
		 * Active Tenants
		 */
		activeTenants: () => LocalizedString
		/**
		 * Users
		 */
		users: () => LocalizedString
		/**
		 * API Endpoints
		 */
		apiEndpoints: () => LocalizedString
		/**
		 * stable
		 */
		stable: () => LocalizedString
		/**
		 * Powerful Data Grids
		 */
		powerfulDataGrids: () => LocalizedString
		/**
		 * Editable, sortable, filterable tables for all your data. CRUD operations, bulk actions, nested rows, and multi-select — powered by TanStack Table.
		 */
		powerfulDataGridsDesc: () => LocalizedString
		/**
		 * Rich Visualizations
		 */
		richVisualizations: () => LocalizedString
		/**
		 * 10+ chart types powered by Plotly.js with WebGL support. Line, bar, scatter, 3D surfaces, heatmaps, and more — all interactive and responsive.
		 */
		richVisualizationsDesc: () => LocalizedString
		/**
		 * Multi-tenant Ready
		 */
		multiTenantReady: () => LocalizedString
		/**
		 * CRUD operations scoped per tenant with role-based read/write control. Manage tenants, members, and permissions from a single dashboard.
		 */
		multiTenantReadyDesc: () => LocalizedString
		/**
		 * Tenant Dashboard
		 */
		tenantDashboard: () => LocalizedString
		/**
		 * Manage platform tenants and subscriptions
		 */
		tenantDashboardDesc: () => LocalizedString
		/**
		 * Add, remove, and manage tenant member roles
		 */
		manageMembersQuickDesc: () => LocalizedString
	}
	Auth: {
		/**
		 * Sign in
		 */
		signIn: () => LocalizedString
		/**
		 * Sign in
		 */
		signInTitle: () => LocalizedString
		/**
		 * Choose your preferred sign-in method
		 */
		signInSubtitle: () => LocalizedString
		/**
		 * Sign in with Google
		 */
		signInWithGoogle: () => LocalizedString
		/**
		 * Sign in with Email OTP
		 */
		signInWithEmailOtp: () => LocalizedString
		/**
		 * Or with Email & Password
		 */
		orWithEmailPassword: () => LocalizedString
		/**
		 * Sign in with Email & Password
		 */
		signInWithEmailPassword: () => LocalizedString
		/**
		 * Signing in...
		 */
		signingIn: () => LocalizedString
		/**
		 * Sign up
		 */
		signUp: () => LocalizedString
		/**
		 * Create an account
		 */
		signUpTitle: () => LocalizedString
		/**
		 * Sign up with your email and password
		 */
		signUpSubtitle: () => LocalizedString
		/**
		 * Sign up with Email & Password
		 */
		signUpWithEmailPassword: () => LocalizedString
		/**
		 * Creating account...
		 */
		creatingAccount: () => LocalizedString
		/**
		 * Don't have an account?
		 */
		dontHaveAccount: () => LocalizedString
		/**
		 * Already have an account?
		 */
		alreadyHaveAccount: () => LocalizedString
		/**
		 * Forgot Password?
		 */
		forgotPassword: () => LocalizedString
		/**
		 * Forgot Password
		 */
		forgotPasswordTitle: () => LocalizedString
		/**
		 * Enter your email to receive a password reset link
		 */
		forgotPasswordSubtitle: () => LocalizedString
		/**
		 * Check your inbox
		 */
		checkYourInbox: () => LocalizedString
		/**
		 * Send Reset Link
		 */
		sendResetLink: () => LocalizedString
		/**
		 * Back to Sign In
		 */
		backToSignIn: () => LocalizedString
		/**
		 * If an account exists with this email, you'll receive a link to set your password.
		 */
		resetLinkSentMessage: () => LocalizedString
		/**
		 * Set Your Password
		 */
		setYourPassword: () => LocalizedString
		/**
		 * Enter a new password for your account
		 */
		setPasswordSubtitle: () => LocalizedString
		/**
		 * Set Password
		 */
		setPassword: () => LocalizedString
		/**
		 * Setting password...
		 */
		settingPassword: () => LocalizedString
		/**
		 * Invalid or Expired Link
		 */
		invalidOrExpiredLink: () => LocalizedString
		/**
		 * This password reset link is invalid or has expired. Please request a new one.
		 */
		invalidOrExpiredLinkMessage: () => LocalizedString
		/**
		 * Request New Link
		 */
		requestNewLink: () => LocalizedString
		/**
		 * Verification Failed
		 */
		verificationFailed: () => LocalizedString
		/**
		 * This verification link has expired. Please try signing in again to receive a new verification email.
		 */
		verificationFailedExpired: () => LocalizedString
		/**
		 * This verification link is invalid. Please try signing in again to receive a new verification email.
		 */
		verificationFailedInvalid: () => LocalizedString
		/**
		 * Email Verified!
		 */
		emailVerified: () => LocalizedString
		/**
		 * Your email has been verified successfully. Redirecting to home...
		 */
		emailVerifiedMessage: () => LocalizedString
		/**
		 * Go to Home now
		 */
		goToHome: () => LocalizedString
		/**
		 * Go to Sign In
		 */
		goToSignIn: () => LocalizedString
		/**
		 * Send OTP
		 */
		sendOtp: () => LocalizedString
		/**
		 * Verify OTP
		 */
		verifyOtp: () => LocalizedString
		/**
		 * Verifying...
		 */
		verifying: () => LocalizedString
		/**
		 * Change Email
		 */
		changeEmail: () => LocalizedString
		/**
		 * We sent a verification code to {email}
		 */
		otpSentTo: (arg: { email: string }) => LocalizedString
		/**
		 * We've sent a verification email to {email}. Please check your inbox and click the link to verify your account before signing in.
		 */
		checkInboxMessage: (arg: { email: string }) => LocalizedString
		/**
		 * Password set successfully. You can now sign in.
		 */
		passwordSetSuccess: () => LocalizedString
		/**
		 * Sign in required
		 */
		signInRequired: () => LocalizedString
		/**
		 * You need to be authenticated to access this application.
		 */
		signInRequiredMessage: () => LocalizedString
		/**
		 * Better Auth Demo
		 */
		betterAuthDemo: () => LocalizedString
		/**
		 * Welcome back!
		 */
		welcomeBack: () => LocalizedString
		/**
		 * Sign in to continue
		 */
		signInToContinue: () => LocalizedString
		/**
		 * You are signed in
		 */
		youAreSignedIn: () => LocalizedString
		/**
		 * User Information
		 */
		userInformation: () => LocalizedString
		/**
		 * Sign Out
		 */
		signOutButton: () => LocalizedString
		/**
		 * Or Email & Password
		 */
		orEmailPassword: () => LocalizedString
		/**
		 * Resend verification email
		 */
		resendVerificationEmail: () => LocalizedString
		/**
		 * Verification email sent! Check your inbox.
		 */
		verificationEmailSent: () => LocalizedString
		/**
		 * Min 8 characters with uppercase, lowercase, number, and special character.
		 */
		passwordMinChars: () => LocalizedString
		/**
		 * I agree to the processing of my personal data as described in the
		 */
		consentText: () => LocalizedString
		/**
		 * . You can withdraw consent at any time by deleting your account.
		 */
		consentSuffix: () => LocalizedString
		/**
		 * You must consent to data processing to create an account
		 */
		consentRequired: () => LocalizedString
		/**
		 * By signing in, you agree to our
		 */
		signInConsentPrefix: () => LocalizedString
		/**
		 * and consent to the processing of your personal data.
		 */
		signInConsentSuffix: () => LocalizedString
		/**
		 * User ID
		 */
		userId: () => LocalizedString
	}
	Dashboard: {
		/**
		 * Platform Tenants
		 */
		platformTenantsTitle: () => LocalizedString
		/**
		 * Create, edit, and remove tenants. Super-admin only.
		 */
		platformTenantsSubtitle: () => LocalizedString
		/**
		 * You must be logged in to access this page.
		 */
		mustBeLoggedIn: () => LocalizedString
		/**
		 * Super-admin access required. Your email must be in SUPER_ADMIN_EMAILS.
		 */
		superAdminRequired: () => LocalizedString
		/**
		 * Add tenant
		 */
		addTenant: () => LocalizedString
		/**
		 * Slug (a-z, 0-9, hyphens)
		 */
		slugLabel: () => LocalizedString
		/**
		 * e.g. acme-corp
		 */
		slugPlaceholder: () => LocalizedString
		/**
		 * e.g. Acme Corp
		 */
		namePlaceholder: () => LocalizedString
		/**
		 * {count} tenant{{s|}}
		 */
		tenantCount: (arg: { count: number }) => LocalizedString
		/**
		 * Loading tenants...
		 */
		loadingTenants: () => LocalizedString
		/**
		 * No tenants yet. Add one above.
		 */
		noTenantsYet: () => LocalizedString
		/**
		 * Refresh list
		 */
		refreshList: () => LocalizedString
		/**
		 * Delete tenant "{slug}"? This cannot be undone.
		 */
		deleteConfirm: (arg: { slug: string }) => LocalizedString
		/**
		 * Dual Database CRUD Demo
		 */
		dualDatabaseCrudDemo: () => LocalizedString
		/**
		 * Side-by-side comparison of Mongoose (MongoDB) and Prisma (PostgreSQL)
		 */
		crudDemoSubtitle: () => LocalizedString
		/**
		 * NextJs (TailwindCSS) • NestJs • tRPC • Transactions
		 */
		crudDemoTechStack: () => LocalizedString
		/**
		 * → Tenant Dashboard (super-admin)
		 */
		tenantDashboardLink: () => LocalizedString
		/**
		 * Global CRUD Demo
		 */
		globalCrudDemoTitle: () => LocalizedString
		/**
		 * Same as CRUD but shared across all tenants. Everyone sees and edits the same data.
		 */
		globalCrudDemoSubtitle: () => LocalizedString
		/**
		 * Mongoose (MongoDB) & Prisma (PostgreSQL) • No tenant scope
		 */
		globalCrudDemoTechStack: () => LocalizedString
		/**
		 * Add text here
		 */
		addTextPlaceholder: () => LocalizedString
	}
	Settings: {
		/**
		 * Profile
		 */
		profileTitle: () => LocalizedString
		/**
		 * Manage your account security and linked sign-in methods.
		 */
		profileSubtitle: () => LocalizedString
		/**
		 * Your email is not verified
		 */
		emailNotVerified: () => LocalizedString
		/**
		 * Please verify your email to access all features.
		 */
		verifyEmailPrompt: () => LocalizedString
		/**
		 * Account Info
		 */
		accountInfo: () => LocalizedString
		/**
		 * Linked Accounts
		 */
		linkedAccounts: () => LocalizedString
		/**
		 * Google
		 */
		google: () => LocalizedString
		/**
		 * Connected
		 */
		connected: () => LocalizedString
		/**
		 * Connect Google
		 */
		connectGoogle: () => LocalizedString
		/**
		 * Email & Password
		 */
		emailAndPassword: () => LocalizedString
		/**
		 * Password set
		 */
		passwordSet: () => LocalizedString
		/**
		 * Not set
		 */
		notSet: () => LocalizedString
		/**
		 * Password
		 */
		passwordTitle: () => LocalizedString
		/**
		 * Change Password
		 */
		changePassword: () => LocalizedString
		/**
		 * Current Password
		 */
		currentPassword: () => LocalizedString
		/**
		 * New Password (min 8 characters)
		 */
		newPasswordLabel: () => LocalizedString
		/**
		 * Confirm New Password
		 */
		confirmNewPassword: () => LocalizedString
		/**
		 * Save Password
		 */
		savePassword: () => LocalizedString
		/**
		 * Add a password to sign in without Google or OTP.
		 */
		addPasswordDescription: () => LocalizedString
		/**
		 * Check your inbox to set your password.
		 */
		checkInboxForPassword: () => LocalizedString
		/**
		 * Manage Members
		 */
		manageMembersTitle: () => LocalizedString
		/**
		 * Add or remove members from your tenants.
		 */
		manageMembersSubtitle: () => LocalizedString
		/**
		 * No admin access
		 */
		noAdminAccess: () => LocalizedString
		/**
		 * You don't have admin access to any tenants.
		 */
		noAdminAccessMessage: () => LocalizedString
		/**
		 * Your tenants ({count})
		 */
		yourTenants: (arg: { count: number }) => LocalizedString
		/**
		 * Members of {name}
		 */
		membersOf: (arg: { name: string }) => LocalizedString
		/**
		 * Add member
		 */
		addMember: () => LocalizedString
		/**
		 * user@example.com
		 */
		memberEmailPlaceholder: () => LocalizedString
		/**
		 * Loading members...
		 */
		loadingMembers: () => LocalizedString
		/**
		 * No members yet. Add one above.
		 */
		noMembersYet: () => LocalizedString
		/**
		 * Remove member
		 */
		removeMember: () => LocalizedString
		/**
		 * Select a tenant from the list to manage its members.
		 */
		selectTenantPrompt: () => LocalizedString
		/**
		 * Edit Profile
		 */
		editProfile: () => LocalizedString
		/**
		 * Edit Name
		 */
		editName: () => LocalizedString
		/**
		 * Full Name
		 */
		fullName: () => LocalizedString
		/**
		 * Your full name
		 */
		fullNamePlaceholder: () => LocalizedString
		/**
		 * 2-100 characters. Letters, spaces, hyphens, and apostrophes only.
		 */
		nameHint: () => LocalizedString
		/**
		 * Name updated successfully
		 */
		nameUpdated: () => LocalizedString
		/**
		 * Failed to update name
		 */
		failedUpdateName: () => LocalizedString
		/**
		 * Data & Privacy
		 */
		dataAndPrivacy: () => LocalizedString
		/**
		 * You have the right to access, export, and delete your personal data at any time. Read our
		 */
		dataPrivacyDescription: () => LocalizedString
		/**
		 * Privacy & Data Policy
		 */
		privacyAndDataPolicy: () => LocalizedString
		/**
		 * Download My Data
		 */
		downloadMyData: () => LocalizedString
		/**
		 * Export all your personal data as a JSON file
		 */
		downloadMyDataDescription: () => LocalizedString
		/**
		 * Preparing export...
		 */
		preparingExport: () => LocalizedString
		/**
		 * Downloaded
		 */
		downloaded: () => LocalizedString
		/**
		 * Download
		 */
		download: () => LocalizedString
		/**
		 * Delete Account
		 */
		deleteAccount: () => LocalizedString
		/**
		 * Permanently delete your account and all associated data
		 */
		deleteAccountDescription: () => LocalizedString
		/**
		 * This action is irreversible. Type your email address
		 */
		deleteConfirmPrefix: () => LocalizedString
		/**
		 * to confirm.
		 */
		deleteConfirmSuffix: () => LocalizedString
		/**
		 * Type your email to confirm
		 */
		typeEmailToConfirm: () => LocalizedString
		/**
		 * Deleting...
		 */
		deleting: () => LocalizedString
		/**
		 * Permanently Delete Account
		 */
		permanentlyDeleteAccount: () => LocalizedString
		/**
		 * Failed to delete account
		 */
		failedDeleteAccount: () => LocalizedString
	}
	Forms: {
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Email Address
		 */
		emailAddress: () => LocalizedString
		/**
		 * you@example.com
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * Enter your email
		 */
		enterYourEmail: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * ••••••••
		 */
		passwordPlaceholder: () => LocalizedString
		/**
		 * Password (min 8 characters)
		 */
		passwordMinChars: () => LocalizedString
		/**
		 * Confirm Password
		 */
		confirmPassword: () => LocalizedString
		/**
		 * First Name
		 */
		firstName: () => LocalizedString
		/**
		 * John
		 */
		firstNamePlaceholder: () => LocalizedString
		/**
		 * Last Name
		 */
		lastName: () => LocalizedString
		/**
		 * Doe
		 */
		lastNamePlaceholder: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Your name
		 */
		namePlaceholder: () => LocalizedString
		/**
		 * Verification Code
		 */
		verificationCode: () => LocalizedString
		/**
		 * Enter 6-digit code
		 */
		verificationCodePlaceholder: () => LocalizedString
		/**
		 * Slug
		 */
		slug: () => LocalizedString
	}
	Errors: {
		/**
		 * Failed to sign in with Google
		 */
		failedSignInGoogle: () => LocalizedString
		/**
		 * Failed to send OTP. Please try again.
		 */
		failedSendOtp: () => LocalizedString
		/**
		 * Unable to send OTP
		 */
		unableToSendOtp: () => LocalizedString
		/**
		 * Invalid OTP. Please try again.
		 */
		invalidOtp: () => LocalizedString
		/**
		 * Unable to verify OTP
		 */
		unableToVerifyOtp: () => LocalizedString
		/**
		 * Please verify your email address before signing in.
		 */
		verifyEmailBeforeSignIn: () => LocalizedString
		/**
		 * This account was created with Google or OTP. Use 'Forgot Password' below to set a password.
		 */
		accountCreatedWithSocial: () => LocalizedString
		/**
		 * Invalid email or password.
		 */
		invalidEmailOrPassword: () => LocalizedString
		/**
		 * Passwords do not match.
		 */
		passwordsDoNotMatch: () => LocalizedString
		/**
		 * Password must be at least 8 characters.
		 */
		passwordMinLength: () => LocalizedString
		/**
		 * Password must be at most 128 characters.
		 */
		passwordMaxLength: () => LocalizedString
		/**
		 * Password must contain at least one uppercase letter.
		 */
		passwordUppercase: () => LocalizedString
		/**
		 * Password must contain at least one lowercase letter.
		 */
		passwordLowercase: () => LocalizedString
		/**
		 * Password must contain at least one number.
		 */
		passwordNumber: () => LocalizedString
		/**
		 * Password must contain at least one special character.
		 */
		passwordSpecialChar: () => LocalizedString
		/**
		 * Failed to reset password. Please try again.
		 */
		failedResetPassword: () => LocalizedString
		/**
		 * Failed to change password.
		 */
		failedChangePassword: () => LocalizedString
		/**
		 * Password changed successfully.
		 */
		passwordChangedSuccess: () => LocalizedString
		/**
		 * Sign up failed. Please try again.
		 */
		signUpFailed: () => LocalizedString
		/**
		 * Sign in failed
		 */
		signInFailed: () => LocalizedString
		/**
		 * An account with this email already exists. Try signing in instead — if you used Google or OTP, you can set a password from your profile.
		 */
		accountAlreadyExists: () => LocalizedString
		/**
		 * {label} is required.
		 */
		nameRequired: (arg: { label: string }) => LocalizedString
		/**
		 * {label} must be at least 2 characters.
		 */
		nameMinLength: (arg: { label: string }) => LocalizedString
		/**
		 * {label} can only contain letters, spaces, hyphens, and apostrophes.
		 */
		nameInvalidChars: (arg: { label: string }) => LocalizedString
		/**
		 * Email is required.
		 */
		emailRequired: () => LocalizedString
		/**
		 * Please enter a valid email address.
		 */
		emailInvalid: () => LocalizedString
		/**
		 * Password is required.
		 */
		passwordRequired: () => LocalizedString
		/**
		 * Slug is required
		 */
		slugRequired: () => LocalizedString
		/**
		 * Name is required
		 */
		nameFieldRequired: () => LocalizedString
		/**
		 * Slug must be lowercase letters, numbers, and hyphens only
		 */
		slugInvalid: () => LocalizedString
		/**
		 * No tenants assigned
		 */
		noTenantsAssigned: () => LocalizedString
		/**
		 * You don't have access to any tenants yet. Please contact an administrator to get added to a tenant.
		 */
		noTenantsMessage: () => LocalizedString
		/**
		 * Loading your tenants...
		 */
		loadingYourTenants: () => LocalizedString
		/**
		 * Setting up your tenant...
		 */
		settingUpTenant: () => LocalizedString
	}
	Sidebar: {
		/**
		 * Navigation
		 */
		navigation: () => LocalizedString
		/**
		 * Main
		 */
		sectionMain: () => LocalizedString
		/**
		 * Data
		 */
		sectionData: () => LocalizedString
		/**
		 * Platform
		 */
		sectionPlatform: () => LocalizedString
		/**
		 * Account
		 */
		sectionAccount: () => LocalizedString
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * CRUD Demo
		 */
		crudDemo: () => LocalizedString
		/**
		 * Global CRUD Demo
		 */
		globalCrudDemo: () => LocalizedString
		/**
		 * Grids
		 */
		grids: () => LocalizedString
		/**
		 * Charts
		 */
		charts: () => LocalizedString
		/**
		 * Tenant Dashboard
		 */
		tenantDashboard: () => LocalizedString
		/**
		 * Tenant Members
		 */
		tenantMembers: () => LocalizedString
		/**
		 * Profile
		 */
		profile: () => LocalizedString
		/**
		 * Crud Records
		 */
		crudRecords: () => LocalizedString
		/**
		 * Global Crud Records
		 */
		globalCrudRecords: () => LocalizedString
		/**
		 * Editable People (Demo)
		 */
		editablePeople: () => LocalizedString
		/**
		 * Batch Ops (Demo)
		 */
		batchOps: () => LocalizedString
		/**
		 * Tenants (Demo)
		 */
		tenantsDemo: () => LocalizedString
		/**
		 * Metrics (Demo)
		 */
		metricsDemo: () => LocalizedString
		/**
		 * Tasks (Demo)
		 */
		tasksDemo: () => LocalizedString
		/**
		 * Overview Charts
		 */
		overviewCharts: () => LocalizedString
		/**
		 * Time Series
		 */
		timeSeries: () => LocalizedString
		/**
		 * Distribution Charts
		 */
		distributionCharts: () => LocalizedString
		/**
		 * Comparative Charts
		 */
		comparativeCharts: () => LocalizedString
		/**
		 * 3D & Advanced
		 */
		threeDAdvanced: () => LocalizedString
	}
	Grids: {
		/**
		 * Data Grids
		 */
		title: () => LocalizedString
		/**
		 * Grid scenarios powered by TanStack Table v8. Grids marked
		 */
		descriptionPrefix: () => LocalizedString
		/**
		 * Demo
		 */
		demo: () => LocalizedString
		/**
		 * use illustrative dummy data. Grids marked
		 */
		descriptionMiddle: () => LocalizedString
		/**
		 * Live
		 */
		live: () => LocalizedString
		/**
		 * fetch real data from the API.
		 */
		descriptionSuffix: () => LocalizedString
		/**
		 * Crud Records
		 */
		tabCrudRecords: () => LocalizedString
		/**
		 * Global Crud Records
		 */
		tabGlobalCrudRecords: () => LocalizedString
		/**
		 * Editable People (Demo)
		 */
		tabEditablePeople: () => LocalizedString
		/**
		 * Batch Operations (Demo)
		 */
		tabBatchOps: () => LocalizedString
		/**
		 * Tenants (Demo)
		 */
		tabTenants: () => LocalizedString
		/**
		 * Metrics (Demo)
		 */
		tabMetrics: () => LocalizedString
		/**
		 * Tasks (Demo)
		 */
		tabTasks: () => LocalizedString
		/**
		 * Live read-only view of Crud records fetched from the API (Prisma). Reflects actual database state.
		 */
		descCrudLive: () => LocalizedString
		/**
		 * Live read-only view of Global Crud records fetched from the API (Prisma). No tenant scoping.
		 */
		descGlobalCrudLive: () => LocalizedString
		/**
		 * Demo: Editable grid with in-memory data modeled after the Crud entity shape.
		 */
		descCrud: () => LocalizedString
		/**
		 * Demo: Bulk operations with row selection, multi-sort, and batch actions on in-memory data.
		 */
		descGlobalCrud: () => LocalizedString
		/**
		 * Demo: Tenant management view grouped by plan tier with expandable sub-rows.
		 */
		descTenants: () => LocalizedString
		/**
		 * Demo: Read-only analytics metrics. Illustrative dummy data, not from a live API.
		 */
		descReadOnly: () => LocalizedString
		/**
		 * Demo: Rich cell renderers with tags, avatars, priority icons, and expandable details.
		 */
		descAdvanced: () => LocalizedString
		/**
		 * ID
		 */
		colId: () => LocalizedString
		/**
		 * Content
		 */
		colContent: () => LocalizedString
		/**
		 * Created At
		 */
		colCreatedAt: () => LocalizedString
		/**
		 * Updated At
		 */
		colUpdatedAt: () => LocalizedString
		/**
		 * First Name
		 */
		colFirstName: () => LocalizedString
		/**
		 * Last Name
		 */
		colLastName: () => LocalizedString
		/**
		 * Email
		 */
		colEmail: () => LocalizedString
		/**
		 * Role
		 */
		colRole: () => LocalizedString
		/**
		 * Status
		 */
		colStatus: () => LocalizedString
		/**
		 * Created
		 */
		colCreated: () => LocalizedString
		/**
		 * Tenant Name
		 */
		colTenantName: () => LocalizedString
		/**
		 * Plan
		 */
		colPlan: () => LocalizedString
		/**
		 * Users
		 */
		colUsers: () => LocalizedString
		/**
		 * Storage
		 */
		colStorage: () => LocalizedString
		/**
		 * Region
		 */
		colRegion: () => LocalizedString
		/**
		 * Metric
		 */
		colMetric: () => LocalizedString
		/**
		 * Value
		 */
		colValue: () => LocalizedString
		/**
		 * Change
		 */
		colChange: () => LocalizedString
		/**
		 * Period
		 */
		colPeriod: () => LocalizedString
		/**
		 * Category
		 */
		colCategory: () => LocalizedString
		/**
		 * Task
		 */
		colTask: () => LocalizedString
		/**
		 * Tags
		 */
		colTags: () => LocalizedString
		/**
		 * Assigned To
		 */
		colAssignedTo: () => LocalizedString
		/**
		 * Priority
		 */
		colPriority: () => LocalizedString
		/**
		 * Due Date
		 */
		colDueDate: () => LocalizedString
		/**
		 * Completed
		 */
		colCompleted: () => LocalizedString
		/**
		 * Admin
		 */
		roleAdmin: () => LocalizedString
		/**
		 * User
		 */
		roleUser: () => LocalizedString
		/**
		 * Editor
		 */
		roleEditor: () => LocalizedString
		/**
		 * Viewer
		 */
		roleViewer: () => LocalizedString
		/**
		 * Active
		 */
		statusActive: () => LocalizedString
		/**
		 * Inactive
		 */
		statusInactive: () => LocalizedString
		/**
		 * Suspended
		 */
		statusSuspended: () => LocalizedString
		/**
		 * Trial
		 */
		statusTrial: () => LocalizedString
		/**
		 * Free
		 */
		planFree: () => LocalizedString
		/**
		 * Pro
		 */
		planPro: () => LocalizedString
		/**
		 * Enterprise
		 */
		planEnterprise: () => LocalizedString
		/**
		 * Live — Prisma
		 */
		livePrisma: () => LocalizedString
		/**
		 * {count} record{{s|}}
		 */
		recordCount: (arg: { count: number }) => LocalizedString
		/**
		 * Loading Crud records…
		 */
		loadingCrudRecords: () => LocalizedString
		/**
		 * Loading Global Crud records…
		 */
		loadingGlobalCrudRecords: () => LocalizedString
		/**
		 * Failed to load: {message}
		 */
		failedToLoad: (arg: { message: string }) => LocalizedString
		/**
		 * Demo — in-memory data
		 */
		demoInMemory: () => LocalizedString
		/**
		 * Demo — dummy data
		 */
		demoDummyData: () => LocalizedString
		/**
		 * Demo — dummy data ({count} records)
		 */
		demoDummyDataCount: (arg: { count: number }) => LocalizedString
		/**
		 * Unsaved changes
		 */
		unsavedChanges: () => LocalizedString
		/**
		 * Add Row
		 */
		addRow: () => LocalizedString
		/**
		 * {count} selected
		 */
		selectedCount: (arg: { count: number }) => LocalizedString
		/**
		 * Delete Selected
		 */
		deleteSelected: () => LocalizedString
		/**
		 * Export
		 */
		'export': () => LocalizedString
		/**
		 * Change Status
		 */
		changeStatus: () => LocalizedString
		/**
		 * Users in {name}
		 */
		usersIn: (arg: { name: string }) => LocalizedString
		/**
		 * User {n}
		 */
		userN: (arg: { n: number }) => LocalizedString
		/**
		 * +{count} more
		 */
		moreUsers: (arg: { count: number }) => LocalizedString
		/**
		 * Done
		 */
		done: () => LocalizedString
		/**
		 * Open
		 */
		open: () => LocalizedString
		/**
		 * Assigned to {name}
		 */
		assignedToLabel: (arg: { name: string }) => LocalizedString
		/**
		 * Priority: {value}
		 */
		priorityLabel: (arg: { value: string }) => LocalizedString
		/**
		 * Due: {date}
		 */
		dueLabel: (arg: { date: string }) => LocalizedString
		/**
		 * OVERDUE
		 */
		overdue: () => LocalizedString
	}
	Charts: {
		/**
		 * Charts & Visualizations
		 */
		title: () => LocalizedString
		/**
		 * 12+ chart types powered by Plotly.js with WebGL support. All charts are interactive — zoom, pan, and hover for details.
		 */
		description: () => LocalizedString
		/**
		 * Line & Area
		 */
		navLineArea: () => LocalizedString
		/**
		 * Bar & Column
		 */
		navBarColumn: () => LocalizedString
		/**
		 * Pie, Donut & Sunburst
		 */
		navPieDonut: () => LocalizedString
		/**
		 * Scatter & Bubble
		 */
		navScatterBubble: () => LocalizedString
		/**
		 * Statistical
		 */
		navStatistical: () => LocalizedString
		/**
		 * Heatmap & Timeline
		 */
		navHeatmapTimeline: () => LocalizedString
		/**
		 * 3D Charts
		 */
		nav3dCharts: () => LocalizedString
		/**
		 * Mixed / Combo
		 */
		navMixedCombo: () => LocalizedString
		/**
		 * Plotly Table
		 */
		navPlotlyTable: () => LocalizedString
		/**
		 * Line & Area Charts
		 */
		lineAreaCharts: () => LocalizedString
		/**
		 * Bar & Column Charts
		 */
		barColumnCharts: () => LocalizedString
		/**
		 * Pie, Donut & Sunburst
		 */
		pieDonutSunburst: () => LocalizedString
		/**
		 * Scatter & Bubble Charts
		 */
		scatterBubbleCharts: () => LocalizedString
		/**
		 * Statistical Charts
		 */
		statisticalCharts: () => LocalizedString
		/**
		 * Heatmap & Timeline
		 */
		heatmapTimeline: () => LocalizedString
		/**
		 * 3D Charts (WebGL)
		 */
		threeDChartsWebGL: () => LocalizedString
		/**
		 * Mixed / Combo Charts
		 */
		mixedComboCharts: () => LocalizedString
		/**
		 * Plotly Table
		 */
		plotlyTable: () => LocalizedString
		/**
		 * User Growth Over Time
		 */
		userGrowthTitle: () => LocalizedString
		/**
		 * 24-month trend of new, active, and churned users.
		 */
		userGrowthDesc: () => LocalizedString
		/**
		 * New Users
		 */
		newUsers: () => LocalizedString
		/**
		 * Active Users
		 */
		activeUsers: () => LocalizedString
		/**
		 * Churned Users
		 */
		churnedUsers: () => LocalizedString
		/**
		 * Revenue Breakdown by Category
		 */
		revenueBreakdownTitle: () => LocalizedString
		/**
		 * Stacked area showing subscription, add-on, service, and overage revenue.
		 */
		revenueBreakdownDesc: () => LocalizedString
		/**
		 * Subscriptions
		 */
		subscriptions: () => LocalizedString
		/**
		 * Add-ons
		 */
		addOns: () => LocalizedString
		/**
		 * Services
		 */
		services: () => LocalizedString
		/**
		 * Overages
		 */
		overages: () => LocalizedString
		/**
		 * Monthly Active Users by Region
		 */
		mauByRegionTitle: () => LocalizedString
		/**
		 * Grouped bar chart comparing four regions over 12 months.
		 */
		mauByRegionDesc: () => LocalizedString
		/**
		 * US-East
		 */
		usEast: () => LocalizedString
		/**
		 * EU-West
		 */
		euWest: () => LocalizedString
		/**
		 * APAC
		 */
		apac: () => LocalizedString
		/**
		 * US-West
		 */
		usWest: () => LocalizedString
		/**
		 * Feature Usage by Tenant Plan
		 */
		featureUsageTitle: () => LocalizedString
		/**
		 * Horizontal stacked bar showing feature adoption across plan tiers.
		 */
		featureUsageDesc: () => LocalizedString
		/**
		 * Auth
		 */
		auth: () => LocalizedString
		/**
		 * CRUD
		 */
		crud: () => LocalizedString
		/**
		 * Analytics
		 */
		analytics: () => LocalizedString
		/**
		 * API
		 */
		api: () => LocalizedString
		/**
		 * Multi-Tenant
		 */
		multiTenant: () => LocalizedString
		/**
		 * Tenant Plan Distribution
		 */
		tenantPlanDistTitle: () => LocalizedString
		/**
		 * Donut chart showing the breakdown of tenants by plan tier.
		 */
		tenantPlanDistDesc: () => LocalizedString
		/**
		 * User Role Hierarchy
		 */
		roleHierarchyTitle: () => LocalizedString
		/**
		 * Sunburst chart showing organizational structure: Org > Department > Role.
		 */
		roleHierarchyDesc: () => LocalizedString
		/**
		 * Session Duration vs. Actions Taken
		 */
		sessionScatterTitle: () => LocalizedString
		/**
		 * Color-encoded by user tier. Hover for details.
		 */
		sessionScatterDesc: () => LocalizedString
		/**
		 * Free
		 */
		free: () => LocalizedString
		/**
		 * Pro
		 */
		pro: () => LocalizedString
		/**
		 * Enterprise
		 */
		enterprise: () => LocalizedString
		/**
		 * Duration (min)
		 */
		durationMin: () => LocalizedString
		/**
		 * Actions
		 */
		actions: () => LocalizedString
		/**
		 * Tenant Size vs. Storage Used
		 */
		tenantBubbleTitle: () => LocalizedString
		/**
		 * Bubble size represents monthly revenue.
		 */
		tenantBubbleDesc: () => LocalizedString
		/**
		 * Revenue ($)
		 */
		revenueUsd: () => LocalizedString
		/**
		 * User Count
		 */
		userCount: () => LocalizedString
		/**
		 * Storage (GB)
		 */
		storageGb: () => LocalizedString
		/**
		 * Response Time Distribution by Service
		 */
		responseTimeTitle: () => LocalizedString
		/**
		 * Box plot showing latency spread across five API services.
		 */
		responseTimeDesc: () => LocalizedString
		/**
		 * Response Time (ms)
		 */
		responseTimeMs: () => LocalizedString
		/**
		 * User Session Length Distribution
		 */
		sessionLengthTitle: () => LocalizedString
		/**
		 * Histogram binned by minute intervals.
		 */
		sessionLengthDesc: () => LocalizedString
		/**
		 * Session Length (min)
		 */
		sessionLengthMin: () => LocalizedString
		/**
		 * Count
		 */
		count: () => LocalizedString
		/**
		 * Activity by Hour and Day of Week
		 */
		activityHeatmapTitle: () => LocalizedString
		/**
		 * 7x24 heatmap showing event density. Viridis colorscale.
		 */
		activityHeatmapDesc: () => LocalizedString
		/**
		 * Tenant Onboarding Timeline
		 */
		ganttTitle: () => LocalizedString
		/**
		 * Gantt-style horizontal bar showing onboarding start and end dates.
		 */
		ganttDesc: () => LocalizedString
		/**
		 * 3D User Engagement Clustering
		 */
		engagement3dTitle: () => LocalizedString
		/**
		 * WebGL-rendered 3D scatter: sessions x avg duration x revenue, colored by cluster tier.
		 */
		engagement3dDesc: () => LocalizedString
		/**
		 * Low
		 */
		low: () => LocalizedString
		/**
		 * Medium
		 */
		medium: () => LocalizedString
		/**
		 * High
		 */
		high: () => LocalizedString
		/**
		 * Sessions
		 */
		sessions: () => LocalizedString
		/**
		 * Avg Duration
		 */
		avgDuration: () => LocalizedString
		/**
		 * Revenue Surface: Time x Region
		 */
		surfaceTitle: () => LocalizedString
		/**
		 * Full 3D rotation — drag to explore. Portland colorscale.
		 */
		surfaceDesc: () => LocalizedString
		/**
		 * Month
		 */
		month: () => LocalizedString
		/**
		 * Region
		 */
		region: () => LocalizedString
		/**
		 * Revenue ($K)
		 */
		revenueK: () => LocalizedString
		/**
		 * Revenue vs. User Growth
		 */
		comboTitle: () => LocalizedString
		/**
		 * Bar chart (revenue) with line overlay (user count) on secondary y-axis.
		 */
		comboDesc: () => LocalizedString
		/**
		 * MRR Movement This Quarter
		 */
		waterfallTitle: () => LocalizedString
		/**
		 * Waterfall chart showing new business, expansion, churn, and net MRR.
		 */
		waterfallDesc: () => LocalizedString
		/**
		 * MRR ($)
		 */
		mrrUsd: () => LocalizedString
		/**
		 * Top 10 Tenants — Plotly Table Trace
		 */
		plotlyTableTitle: () => LocalizedString
		/**
		 * This is a Plotly trace, not TanStack Table — compare the two on the Grids page.
		 */
		plotlyTableDesc: () => LocalizedString
	}
	CookieBanner: {
		/**
		 * This site uses essential cookies to keep you signed in. No tracking or advertising cookies.
		 */
		text: () => LocalizedString
		/**
		 * Learn more
		 */
		learnMore: () => LocalizedString
		/**
		 * Got it
		 */
		gotIt: () => LocalizedString
	}
	Privacy: {
		/**
		 * Privacy & Data Policy
		 */
		title: () => LocalizedString
		/**
		 * Last updated: February 20, 2026
		 */
		lastUpdated: () => LocalizedString
		/**
		 * 1. What data we collect
		 */
		section1Title: () => LocalizedString
		/**
		 * When you create an account we store:
		 */
		section1Intro: () => LocalizedString
		/**
		 * Name and email
		 */
		collectName: () => LocalizedString
		/**
		 * — provided by you or your Google account.
		 */
		collectNameDetail: () => LocalizedString
		/**
		 * Profile picture URL
		 */
		collectImage: () => LocalizedString
		/**
		 * — from Google if you sign in with Google.
		 */
		collectImageDetail: () => LocalizedString
		/**
		 * Password
		 */
		collectPassword: () => LocalizedString
		/**
		 * — if you use email/password sign-in. Stored encrypted; we never see or store it in plain text.
		 */
		collectPasswordDetail: () => LocalizedString
		/**
		 * OAuth tokens
		 */
		collectOAuth: () => LocalizedString
		/**
		 * — if you sign in with Google. Stored encrypted. Used to maintain your Google session and access Google Drive on your behalf if you granted those permissions.
		 */
		collectOAuthDetail: () => LocalizedString
		/**
		 * IP address and user agent
		 */
		collectIp: () => LocalizedString
		/**
		 * — recorded per session for security and audit purposes.
		 */
		collectIpDetail: () => LocalizedString
		/**
		 * Consent timestamp and IP
		 */
		collectConsent: () => LocalizedString
		/**
		 * — recorded when you agree to this policy.
		 */
		collectConsentDetail: () => LocalizedString
		/**
		 * 2. How we use your data
		 */
		section2Title: () => LocalizedString
		/**
		 * Authentication
		 */
		useAuth: () => LocalizedString
		/**
		 * — to sign you in, verify your email, and manage your sessions.
		 */
		useAuthDetail: () => LocalizedString
		/**
		 * Account management
		 */
		useAccount: () => LocalizedString
		/**
		 * — to display your profile and let you update or delete it.
		 */
		useAccountDetail: () => LocalizedString
		/**
		 * Transactional emails
		 */
		useEmail: () => LocalizedString
		/**
		 * — to send OTPs, verification links, and password reset links. We never send marketing email.
		 */
		useEmailDetail: () => LocalizedString
		/**
		 * Security
		 */
		useSecurity: () => LocalizedString
		/**
		 * — to detect suspicious activity and maintain audit logs.
		 */
		useSecurityDetail: () => LocalizedString
		/**
		 * Google Drive
		 */
		useDrive: () => LocalizedString
		/**
		 * — if you granted Drive scopes, to read or create files in your Drive on your behalf. We do not access Drive without your explicit scope grant.
		 */
		useDriveDetail: () => LocalizedString
		/**
		 * We do not sell, share, or rent your personal data to third parties. We do not use your data for advertising or profiling.
		 */
		noSellData: () => LocalizedString
		/**
		 * 3. Cookies
		 */
		section3Title: () => LocalizedString
		/**
		 * We use
		 */
		cookiesIntro: () => LocalizedString
		/**
		 * strictly necessary cookies only
		 */
		cookiesIntroStrict: () => LocalizedString
		/**
		 * . No analytics, advertising, or tracking cookies.
		 */
		cookiesIntroSuffix: () => LocalizedString
		/**
		 * Cookie
		 */
		cookieHeader: () => LocalizedString
		/**
		 * Purpose
		 */
		purposeHeader: () => LocalizedString
		/**
		 * Expiry
		 */
		expiryHeader: () => LocalizedString
		/**
		 * Session Token
		 */
		cookieSessionToken: () => LocalizedString
		/**
		 * Keeps you signed in across visits
		 */
		cookieSessionPurpose: () => LocalizedString
		/**
		 * 7 days
		 */
		cookieSessionExpiry: () => LocalizedString
		/**
		 * OAuth State
		 */
		cookieOAuthState: () => LocalizedString
		/**
		 * Temporary token to secure the Google sign-in flow
		 */
		cookieOAuthPurpose: () => LocalizedString
		/**
		 * 3 days
		 */
		cookieOAuthExpiry: () => LocalizedString
		/**
		 * These cookies are required for the application to function. They cannot be used to track you across other websites.
		 */
		cookiesFootnote: () => LocalizedString
		/**
		 * 4. Third-party services
		 */
		section4Title: () => LocalizedString
		/**
		 * Google (OAuth)
		 */
		thirdPartyGoogle: () => LocalizedString
		/**
		 * — for sign-in and Drive access. Subject to
		 */
		thirdPartyGoogleDetail: () => LocalizedString
		/**
		 * Google's Privacy Policy
		 */
		googlePrivacyPolicy: () => LocalizedString
		/**
		 * Amazon Web Services (SES)
		 */
		thirdPartyAws: () => LocalizedString
		/**
		 * — to deliver transactional emails. AWS processes recipient email addresses solely for delivery.
		 */
		thirdPartyAwsDetail: () => LocalizedString
		/**
		 * Rollbar
		 */
		thirdPartyRollbar: () => LocalizedString
		/**
		 * — for error monitoring. Receives error messages and stack traces only; no user PII is intentionally sent.
		 */
		thirdPartyRollbarDetail: () => LocalizedString
		/**
		 * 5. How we protect your data
		 */
		section5Title: () => LocalizedString
		/**
		 * Passwords are stored encrypted and can never be read back.
		 */
		protectPassword: () => LocalizedString
		/**
		 * OAuth tokens are encrypted at rest on our servers.
		 */
		protectOAuth: () => LocalizedString
		/**
		 * Session cookies are secured and signed.
		 */
		protectCookies: () => LocalizedString
		/**
		 * Email addresses are not stored in application logs.
		 */
		protectLogs: () => LocalizedString
		/**
		 * All communication is over HTTPS in production.
		 */
		protectHttps: () => LocalizedString
		/**
		 * 6. Your rights
		 */
		section6Title: () => LocalizedString
		/**
		 * From your profile page you can:
		 */
		rightsIntro: () => LocalizedString
		/**
		 * Access
		 */
		rightAccess: () => LocalizedString
		/**
		 * — download all personal data we hold about you as a JSON file.
		 */
		rightAccessDetail: () => LocalizedString
		/**
		 * Rectify
		 */
		rightRectify: () => LocalizedString
		/**
		 * — update your name and profile picture.
		 */
		rightRectifyDetail: () => LocalizedString
		/**
		 * Delete
		 */
		rightDelete: () => LocalizedString
		/**
		 * — permanently delete your account and all associated data (sessions, OAuth tokens, tenant memberships, verification tokens). This action is irreversible.
		 */
		rightDeleteDetail: () => LocalizedString
		/**
		 * Withdraw consent
		 */
		rightWithdraw: () => LocalizedString
		/**
		 * — by deleting your account.
		 */
		rightWithdrawDetail: () => LocalizedString
		/**
		 * All data subject actions are recorded in an internal audit log.
		 */
		rightsAuditNote: () => LocalizedString
		/**
		 * 7. Data retention
		 */
		section7Title: () => LocalizedString
		/**
		 * Account data is kept for as long as your account exists.
		 */
		retainAccount: () => LocalizedString
		/**
		 * Sessions expire after 7 days.
		 */
		retainSessions: () => LocalizedString
		/**
		 * Verification tokens (email, OTP, password reset) are automatically purged after expiry.
		 */
		retainVerification: () => LocalizedString
		/**
		 * When you delete your account, all personal data is permanently removed. GDPR audit log entries (which contain only your user ID and action type) are retained for legal accountability.
		 */
		retainDeletion: () => LocalizedString
		/**
		 * 8. Contact
		 */
		section8Title: () => LocalizedString
		/**
		 * For privacy-related questions or requests, email us at
		 */
		contactText: () => LocalizedString
	}
}

export type Formatters = {}
