// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en";

export type Locales = "en" | "nl";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  Common: {
    /**
     * L​o​a​d​i​n​g​.​.​.
     */
    loading: string;
    /**
     * B​a​c​k​ ​t​o​ ​H​o​m​e
     */
    backToHome: string;
    /**
     * B​a​c​k
     */
    back: string;
    /**
     * C​a​n​c​e​l
     */
    cancel: string;
    /**
     * S​a​v​e
     */
    save: string;
    /**
     * A​d​d
     */
    add: string;
    /**
     * R​e​f​r​e​s​h
     */
    refresh: string;
    /**
     * R​e​f​r​e​s​h​i​n​g​.​.​.
     */
    refreshing: string;
    /**
     * A​d​d​i​n​g​.​.​.
     */
    adding: string;
    /**
     * S​a​v​i​n​g​.​.​.
     */
    saving: string;
    /**
     * S​e​n​d​i​n​g​.​.​.
     */
    sending: string;
    /**
     * O​r
     */
    or: string;
    /**
     * A​d​m​i​n
     */
    roleAdmin: string;
    /**
     * U​s​e​r
     */
    roleUser: string;
    /**
     * Y​o​u
     */
    you: string;
    /**
     * E​d​i​t
     */
    edit: string;
    /**
     * D​e​l​e​t​e
     */
    delete: string;
    /**
     * L​o​a​d​i​n​g​ ​i​t​e​m​s​.​.​.
     */
    loadingItems: string;
    /**
     * N​o​ ​i​t​e​m​s​ ​y​e​t​.​ ​A​d​d​ ​o​n​e​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​!
     */
    noItemsYet: string;
    /**
     * {​c​o​u​n​t​}​ ​{​{​I​t​e​m​|​I​t​e​m​s​}​}
     * @param {number} count
     */
    itemCount: RequiredParams<"count">;
    /**
     * {​c​o​u​n​t​}​ ​{​{​I​t​e​m​|​I​t​e​m​s​}​}​ ​(​g​l​o​b​a​l​)
     * @param {number} count
     */
    itemCountGlobal: RequiredParams<"count">;
  };
  Navigation: {
    /**
     * F​u​l​l​ ​S​t​a​c​k
     */
    fullStack: string;
    /**
     * P​r​o​f​i​l​e​ ​&​ ​S​e​c​u​r​i​t​y
     */
    profileAndSecurity: string;
    /**
     * P​l​a​t​f​o​r​m​ ​T​e​n​a​n​t​s
     */
    platformTenants: string;
    /**
     * M​a​n​a​g​e​ ​M​e​m​b​e​r​s
     */
    manageMembers: string;
    /**
     * S​i​g​n​ ​o​u​t
     */
    signOut: string;
    /**
     * S​w​i​t​c​h​ ​t​e​n​a​n​t
     */
    switchTenant: string;
    /**
     * S​w​i​t​c​h​i​n​g​.​.​.
     */
    switching: string;
    /**
     * S​e​l​e​c​t​ ​t​e​n​a​n​t
     */
    selectTenant: string;
  };
  Home: {
    /**
     * F​u​l​l​ ​S​t​a​c​k​ ​B​o​i​l​e​r​p​l​a​t​e
     */
    title: string;
    /**
     * N​e​x​t​J​s​ ​(​T​a​i​l​w​i​n​d​ ​C​S​S​)​,​ ​N​e​s​t​J​s​,​ ​E​x​p​o​,​ ​t​R​P​C​,​ ​B​e​t​t​e​r​ ​A​u​t​h
     */
    subtitle: string;
    /**
     * C​R​U​D​ ​D​e​m​o
     */
    crudDemoTitle: string;
    /**
     * T​e​s​t​ ​C​r​e​a​t​e​,​ ​R​e​a​d​,​ ​U​p​d​a​t​e​,​ ​D​e​l​e​t​e​ ​o​p​e​r​a​t​i​o​n​s​ ​w​i​t​h​ ​t​R​P​C​ ​a​n​d​ ​P​r​i​s​m​a​ ​i​n​t​e​g​r​a​t​i​o​n​.​ ​F​u​l​l​-​s​t​a​c​k​ ​t​y​p​e​ ​s​a​f​e​t​y​ ​d​e​m​o​n​s​t​r​a​t​i​o​n​.
     */
    crudDemoDescription: string;
    /**
     * G​l​o​b​a​l​ ​C​R​U​D​ ​D​e​m​o
     */
    globalCrudDemoTitle: string;
    /**
     * S​a​m​e​ ​a​s​ ​C​R​U​D​ ​b​u​t​ ​s​h​a​r​e​d​ ​a​c​r​o​s​s​ ​a​l​l​ ​t​e​n​a​n​t​s​.​ ​E​v​e​r​y​o​n​e​ ​s​e​e​s​ ​a​n​d​ ​e​d​i​t​s​ ​t​h​e​ ​s​a​m​e​ ​d​a​t​a​.
     */
    globalCrudDemoDescription: string;
    /**
     * P​l​a​t​f​o​r​m​ ​T​e​n​a​n​t​s
     */
    platformTenantsTitle: string;
    /**
     * C​r​e​a​t​e​,​ ​e​d​i​t​,​ ​a​n​d​ ​r​e​m​o​v​e​ ​t​e​n​a​n​t​s​ ​a​c​r​o​s​s​ ​t​h​e​ ​p​l​a​t​f​o​r​m​.​ ​S​u​p​e​r​-​a​d​m​i​n​ ​o​n​l​y​.
     */
    platformTenantsDescription: string;
    /**
     * M​a​n​a​g​e​ ​t​e​n​a​n​t​s
     */
    manageTenants: string;
    /**
     * M​a​n​a​g​e​ ​M​e​m​b​e​r​s
     */
    manageMembersTitle: string;
    /**
     * A​d​d​ ​o​r​ ​r​e​m​o​v​e​ ​m​e​m​b​e​r​s​ ​f​r​o​m​ ​t​e​n​a​n​t​s​ ​y​o​u​ ​a​d​m​i​n​i​s​t​e​r​.
     */
    manageMembersDescription: string;
    /**
     * M​a​n​a​g​e​ ​m​e​m​b​e​r​s
     */
    manageMembers: string;
    /**
     * A​u​t​h​ ​D​e​m​o
     */
    authDemoTitle: string;
    /**
     * T​e​s​t​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​w​i​t​h​ ​B​e​t​t​e​r​ ​A​u​t​h​.​ ​O​A​u​t​h​ ​i​n​t​e​g​r​a​t​i​o​n​ ​w​i​t​h​ ​G​o​o​g​l​e​,​ ​s​e​s​s​i​o​n​ ​m​a​n​a​g​e​m​e​n​t​,​ ​a​n​d​ ​p​r​o​t​e​c​t​e​d​ ​r​o​u​t​e​s​.
     */
    authDemoDescription: string;
    /**
     * T​r​y​ ​i​t​ ​o​u​t
     */
    tryItOut: string;
    /**
     * B​u​i​l​t​ ​w​i​t​h​ ​m​o​d​e​r​n​ ​t​o​o​l​s​ ​f​o​r​ ​r​a​p​i​d​ ​d​e​v​e​l​o​p​m​e​n​t
     */
    footer: string;
  };
  Auth: {
    /**
     * S​i​g​n​ ​i​n
     */
    signIn: string;
    /**
     * S​i​g​n​ ​i​n
     */
    signInTitle: string;
    /**
     * C​h​o​o​s​e​ ​y​o​u​r​ ​p​r​e​f​e​r​r​e​d​ ​s​i​g​n​-​i​n​ ​m​e​t​h​o​d
     */
    signInSubtitle: string;
    /**
     * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e
     */
    signInWithGoogle: string;
    /**
     * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​E​m​a​i​l​ ​O​T​P
     */
    signInWithEmailOtp: string;
    /**
     * O​r​ ​w​i​t​h​ ​E​m​a​i​l​ ​&​ ​P​a​s​s​w​o​r​d
     */
    orWithEmailPassword: string;
    /**
     * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​E​m​a​i​l​ ​&​ ​P​a​s​s​w​o​r​d
     */
    signInWithEmailPassword: string;
    /**
     * S​i​g​n​i​n​g​ ​i​n​.​.​.
     */
    signingIn: string;
    /**
     * S​i​g​n​ ​u​p
     */
    signUp: string;
    /**
     * C​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t
     */
    signUpTitle: string;
    /**
     * S​i​g​n​ ​u​p​ ​w​i​t​h​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​n​d​ ​p​a​s​s​w​o​r​d
     */
    signUpSubtitle: string;
    /**
     * S​i​g​n​ ​u​p​ ​w​i​t​h​ ​E​m​a​i​l​ ​&​ ​P​a​s​s​w​o​r​d
     */
    signUpWithEmailPassword: string;
    /**
     * C​r​e​a​t​i​n​g​ ​a​c​c​o​u​n​t​.​.​.
     */
    creatingAccount: string;
    /**
     * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
     */
    dontHaveAccount: string;
    /**
     * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
     */
    alreadyHaveAccount: string;
    /**
     * F​o​r​g​o​t​ ​P​a​s​s​w​o​r​d​?
     */
    forgotPassword: string;
    /**
     * F​o​r​g​o​t​ ​P​a​s​s​w​o​r​d
     */
    forgotPasswordTitle: string;
    /**
     * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​r​e​c​e​i​v​e​ ​a​ ​p​a​s​s​w​o​r​d​ ​r​e​s​e​t​ ​l​i​n​k
     */
    forgotPasswordSubtitle: string;
    /**
     * C​h​e​c​k​ ​y​o​u​r​ ​i​n​b​o​x
     */
    checkYourInbox: string;
    /**
     * S​e​n​d​ ​R​e​s​e​t​ ​L​i​n​k
     */
    sendResetLink: string;
    /**
     * B​a​c​k​ ​t​o​ ​S​i​g​n​ ​I​n
     */
    backToSignIn: string;
    /**
     * I​f​ ​a​n​ ​a​c​c​o​u​n​t​ ​e​x​i​s​t​s​ ​w​i​t​h​ ​t​h​i​s​ ​e​m​a​i​l​,​ ​y​o​u​'​l​l​ ​r​e​c​e​i​v​e​ ​a​ ​l​i​n​k​ ​t​o​ ​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.
     */
    resetLinkSentMessage: string;
    /**
     * S​e​t​ ​Y​o​u​r​ ​P​a​s​s​w​o​r​d
     */
    setYourPassword: string;
    /**
     * E​n​t​e​r​ ​a​ ​n​e​w​ ​p​a​s​s​w​o​r​d​ ​f​o​r​ ​y​o​u​r​ ​a​c​c​o​u​n​t
     */
    setPasswordSubtitle: string;
    /**
     * S​e​t​ ​P​a​s​s​w​o​r​d
     */
    setPassword: string;
    /**
     * S​e​t​t​i​n​g​ ​p​a​s​s​w​o​r​d​.​.​.
     */
    settingPassword: string;
    /**
     * I​n​v​a​l​i​d​ ​o​r​ ​E​x​p​i​r​e​d​ ​L​i​n​k
     */
    invalidOrExpiredLink: string;
    /**
     * T​h​i​s​ ​p​a​s​s​w​o​r​d​ ​r​e​s​e​t​ ​l​i​n​k​ ​i​s​ ​i​n​v​a​l​i​d​ ​o​r​ ​h​a​s​ ​e​x​p​i​r​e​d​.​ ​P​l​e​a​s​e​ ​r​e​q​u​e​s​t​ ​a​ ​n​e​w​ ​o​n​e​.
     */
    invalidOrExpiredLinkMessage: string;
    /**
     * R​e​q​u​e​s​t​ ​N​e​w​ ​L​i​n​k
     */
    requestNewLink: string;
    /**
     * V​e​r​i​f​i​c​a​t​i​o​n​ ​F​a​i​l​e​d
     */
    verificationFailed: string;
    /**
     * T​h​i​s​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​l​i​n​k​ ​h​a​s​ ​e​x​p​i​r​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​s​i​g​n​i​n​g​ ​i​n​ ​a​g​a​i​n​ ​t​o​ ​r​e​c​e​i​v​e​ ​a​ ​n​e​w​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l​.
     */
    verificationFailedExpired: string;
    /**
     * T​h​i​s​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​l​i​n​k​ ​i​s​ ​i​n​v​a​l​i​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​s​i​g​n​i​n​g​ ​i​n​ ​a​g​a​i​n​ ​t​o​ ​r​e​c​e​i​v​e​ ​a​ ​n​e​w​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l​.
     */
    verificationFailedInvalid: string;
    /**
     * E​m​a​i​l​ ​V​e​r​i​f​i​e​d​!
     */
    emailVerified: string;
    /**
     * Y​o​u​r​ ​e​m​a​i​l​ ​h​a​s​ ​b​e​e​n​ ​v​e​r​i​f​i​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​.​ ​R​e​d​i​r​e​c​t​i​n​g​ ​t​o​ ​h​o​m​e​.​.​.
     */
    emailVerifiedMessage: string;
    /**
     * G​o​ ​t​o​ ​H​o​m​e​ ​n​o​w
     */
    goToHome: string;
    /**
     * G​o​ ​t​o​ ​S​i​g​n​ ​I​n
     */
    goToSignIn: string;
    /**
     * S​e​n​d​ ​O​T​P
     */
    sendOtp: string;
    /**
     * V​e​r​i​f​y​ ​O​T​P
     */
    verifyOtp: string;
    /**
     * V​e​r​i​f​y​i​n​g​.​.​.
     */
    verifying: string;
    /**
     * C​h​a​n​g​e​ ​E​m​a​i​l
     */
    changeEmail: string;
    /**
     * W​e​ ​s​e​n​t​ ​a​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​ ​t​o​ ​{​e​m​a​i​l​}
     * @param {string} email
     */
    otpSentTo: RequiredParams<"email">;
    /**
     * W​e​'​v​e​ ​s​e​n​t​ ​a​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l​ ​t​o​ ​{​e​m​a​i​l​}​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​i​n​b​o​x​ ​a​n​d​ ​c​l​i​c​k​ ​t​h​e​ ​l​i​n​k​ ​t​o​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​b​e​f​o​r​e​ ​s​i​g​n​i​n​g​ ​i​n​.
     * @param {string} email
     */
    checkInboxMessage: RequiredParams<"email">;
    /**
     * P​a​s​s​w​o​r​d​ ​s​e​t​ ​s​u​c​c​e​s​s​f​u​l​l​y​.​ ​Y​o​u​ ​c​a​n​ ​n​o​w​ ​s​i​g​n​ ​i​n​.
     */
    passwordSetSuccess: string;
    /**
     * S​i​g​n​ ​i​n​ ​r​e​q​u​i​r​e​d
     */
    signInRequired: string;
    /**
     * Y​o​u​ ​n​e​e​d​ ​t​o​ ​b​e​ ​a​u​t​h​e​n​t​i​c​a​t​e​d​ ​t​o​ ​a​c​c​e​s​s​ ​t​h​i​s​ ​a​p​p​l​i​c​a​t​i​o​n​.
     */
    signInRequiredMessage: string;
    /**
     * B​e​t​t​e​r​ ​A​u​t​h​ ​D​e​m​o
     */
    betterAuthDemo: string;
    /**
     * W​e​l​c​o​m​e​ ​b​a​c​k​!
     */
    welcomeBack: string;
    /**
     * S​i​g​n​ ​i​n​ ​t​o​ ​c​o​n​t​i​n​u​e
     */
    signInToContinue: string;
    /**
     * Y​o​u​ ​a​r​e​ ​s​i​g​n​e​d​ ​i​n
     */
    youAreSignedIn: string;
    /**
     * U​s​e​r​ ​I​n​f​o​r​m​a​t​i​o​n
     */
    userInformation: string;
    /**
     * S​i​g​n​ ​O​u​t
     */
    signOutButton: string;
    /**
     * O​r​ ​E​m​a​i​l​ ​&​ ​P​a​s​s​w​o​r​d
     */
    orEmailPassword: string;
    /**
     * R​e​s​e​n​d​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l
     */
    resendVerificationEmail: string;
    /**
     * V​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l​ ​s​e​n​t​!​ ​C​h​e​c​k​ ​y​o​u​r​ ​i​n​b​o​x​.
     */
    verificationEmailSent: string;
    /**
     * M​i​n​ ​8​ ​c​h​a​r​a​c​t​e​r​s​ ​w​i​t​h​ ​u​p​p​e​r​c​a​s​e​,​ ​l​o​w​e​r​c​a​s​e​,​ ​n​u​m​b​e​r​,​ ​a​n​d​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​.
     */
    passwordMinChars: string;
  };
  Dashboard: {
    /**
     * P​l​a​t​f​o​r​m​ ​T​e​n​a​n​t​s
     */
    platformTenantsTitle: string;
    /**
     * C​r​e​a​t​e​,​ ​e​d​i​t​,​ ​a​n​d​ ​r​e​m​o​v​e​ ​t​e​n​a​n​t​s​.​ ​S​u​p​e​r​-​a​d​m​i​n​ ​o​n​l​y​.
     */
    platformTenantsSubtitle: string;
    /**
     * Y​o​u​ ​m​u​s​t​ ​b​e​ ​l​o​g​g​e​d​ ​i​n​ ​t​o​ ​a​c​c​e​s​s​ ​t​h​i​s​ ​p​a​g​e​.
     */
    mustBeLoggedIn: string;
    /**
     * S​u​p​e​r​-​a​d​m​i​n​ ​a​c​c​e​s​s​ ​r​e​q​u​i​r​e​d​.​ ​Y​o​u​r​ ​e​m​a​i​l​ ​m​u​s​t​ ​b​e​ ​i​n​ ​S​U​P​E​R​_​A​D​M​I​N​_​E​M​A​I​L​S​.
     */
    superAdminRequired: string;
    /**
     * A​d​d​ ​t​e​n​a​n​t
     */
    addTenant: string;
    /**
     * S​l​u​g​ ​(​a​-​z​,​ ​0​-​9​,​ ​h​y​p​h​e​n​s​)
     */
    slugLabel: string;
    /**
     * e​.​g​.​ ​a​c​m​e​-​c​o​r​p
     */
    slugPlaceholder: string;
    /**
     * e​.​g​.​ ​A​c​m​e​ ​C​o​r​p
     */
    namePlaceholder: string;
    /**
     * {​c​o​u​n​t​}​ ​t​e​n​a​n​t​{​{​s​|​}​}
     * @param {number} count
     */
    tenantCount: RequiredParams<"count">;
    /**
     * L​o​a​d​i​n​g​ ​t​e​n​a​n​t​s​.​.​.
     */
    loadingTenants: string;
    /**
     * N​o​ ​t​e​n​a​n​t​s​ ​y​e​t​.​ ​A​d​d​ ​o​n​e​ ​a​b​o​v​e​.
     */
    noTenantsYet: string;
    /**
     * R​e​f​r​e​s​h​ ​l​i​s​t
     */
    refreshList: string;
    /**
     * D​e​l​e​t​e​ ​t​e​n​a​n​t​ ​"​{​s​l​u​g​}​"​?​ ​T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
     * @param {string} slug
     */
    deleteConfirm: RequiredParams<"slug">;
    /**
     * D​u​a​l​ ​D​a​t​a​b​a​s​e​ ​C​R​U​D​ ​D​e​m​o
     */
    dualDatabaseCrudDemo: string;
    /**
     * S​i​d​e​-​b​y​-​s​i​d​e​ ​c​o​m​p​a​r​i​s​o​n​ ​o​f​ ​M​o​n​g​o​o​s​e​ ​(​M​o​n​g​o​D​B​)​ ​a​n​d​ ​P​r​i​s​m​a​ ​(​P​o​s​t​g​r​e​S​Q​L​)
     */
    crudDemoSubtitle: string;
    /**
     * N​e​x​t​J​s​ ​(​T​a​i​l​w​i​n​d​C​S​S​)​ ​•​ ​N​e​s​t​J​s​ ​•​ ​t​R​P​C​ ​•​ ​T​r​a​n​s​a​c​t​i​o​n​s
     */
    crudDemoTechStack: string;
    /**
     * →​ ​T​e​n​a​n​t​ ​D​a​s​h​b​o​a​r​d​ ​(​s​u​p​e​r​-​a​d​m​i​n​)
     */
    tenantDashboardLink: string;
    /**
     * G​l​o​b​a​l​ ​C​R​U​D​ ​D​e​m​o
     */
    globalCrudDemoTitle: string;
    /**
     * S​a​m​e​ ​a​s​ ​C​R​U​D​ ​b​u​t​ ​s​h​a​r​e​d​ ​a​c​r​o​s​s​ ​a​l​l​ ​t​e​n​a​n​t​s​.​ ​E​v​e​r​y​o​n​e​ ​s​e​e​s​ ​a​n​d​ ​e​d​i​t​s​ ​t​h​e​ ​s​a​m​e​ ​d​a​t​a​.
     */
    globalCrudDemoSubtitle: string;
    /**
     * M​o​n​g​o​o​s​e​ ​(​M​o​n​g​o​D​B​)​ ​&​ ​P​r​i​s​m​a​ ​(​P​o​s​t​g​r​e​S​Q​L​)​ ​•​ ​N​o​ ​t​e​n​a​n​t​ ​s​c​o​p​e
     */
    globalCrudDemoTechStack: string;
    /**
     * A​d​d​ ​t​e​x​t​ ​h​e​r​e
     */
    addTextPlaceholder: string;
  };
  Settings: {
    /**
     * P​r​o​f​i​l​e
     */
    profileTitle: string;
    /**
     * M​a​n​a​g​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​s​e​c​u​r​i​t​y​ ​a​n​d​ ​l​i​n​k​e​d​ ​s​i​g​n​-​i​n​ ​m​e​t​h​o​d​s​.
     */
    profileSubtitle: string;
    /**
     * Y​o​u​r​ ​e​m​a​i​l​ ​i​s​ ​n​o​t​ ​v​e​r​i​f​i​e​d
     */
    emailNotVerified: string;
    /**
     * P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​a​c​c​e​s​s​ ​a​l​l​ ​f​e​a​t​u​r​e​s​.
     */
    verifyEmailPrompt: string;
    /**
     * A​c​c​o​u​n​t​ ​I​n​f​o
     */
    accountInfo: string;
    /**
     * L​i​n​k​e​d​ ​A​c​c​o​u​n​t​s
     */
    linkedAccounts: string;
    /**
     * G​o​o​g​l​e
     */
    google: string;
    /**
     * C​o​n​n​e​c​t​e​d
     */
    connected: string;
    /**
     * C​o​n​n​e​c​t​ ​G​o​o​g​l​e
     */
    connectGoogle: string;
    /**
     * E​m​a​i​l​ ​&​ ​P​a​s​s​w​o​r​d
     */
    emailAndPassword: string;
    /**
     * P​a​s​s​w​o​r​d​ ​s​e​t
     */
    passwordSet: string;
    /**
     * N​o​t​ ​s​e​t
     */
    notSet: string;
    /**
     * P​a​s​s​w​o​r​d
     */
    passwordTitle: string;
    /**
     * C​h​a​n​g​e​ ​P​a​s​s​w​o​r​d
     */
    changePassword: string;
    /**
     * C​u​r​r​e​n​t​ ​P​a​s​s​w​o​r​d
     */
    currentPassword: string;
    /**
     * N​e​w​ ​P​a​s​s​w​o​r​d​ ​(​m​i​n​ ​8​ ​c​h​a​r​a​c​t​e​r​s​)
     */
    newPasswordLabel: string;
    /**
     * C​o​n​f​i​r​m​ ​N​e​w​ ​P​a​s​s​w​o​r​d
     */
    confirmNewPassword: string;
    /**
     * S​a​v​e​ ​P​a​s​s​w​o​r​d
     */
    savePassword: string;
    /**
     * A​d​d​ ​a​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​s​i​g​n​ ​i​n​ ​w​i​t​h​o​u​t​ ​G​o​o​g​l​e​ ​o​r​ ​O​T​P​.
     */
    addPasswordDescription: string;
    /**
     * C​h​e​c​k​ ​y​o​u​r​ ​i​n​b​o​x​ ​t​o​ ​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.
     */
    checkInboxForPassword: string;
    /**
     * M​a​n​a​g​e​ ​M​e​m​b​e​r​s
     */
    manageMembersTitle: string;
    /**
     * A​d​d​ ​o​r​ ​r​e​m​o​v​e​ ​m​e​m​b​e​r​s​ ​f​r​o​m​ ​y​o​u​r​ ​t​e​n​a​n​t​s​.
     */
    manageMembersSubtitle: string;
    /**
     * N​o​ ​a​d​m​i​n​ ​a​c​c​e​s​s
     */
    noAdminAccess: string;
    /**
     * Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​d​m​i​n​ ​a​c​c​e​s​s​ ​t​o​ ​a​n​y​ ​t​e​n​a​n​t​s​.
     */
    noAdminAccessMessage: string;
    /**
     * Y​o​u​r​ ​t​e​n​a​n​t​s​ ​(​{​c​o​u​n​t​}​)
     * @param {number} count
     */
    yourTenants: RequiredParams<"count">;
    /**
     * M​e​m​b​e​r​s​ ​o​f​ ​{​n​a​m​e​}
     * @param {string} name
     */
    membersOf: RequiredParams<"name">;
    /**
     * A​d​d​ ​m​e​m​b​e​r
     */
    addMember: string;
    /**
     * u​s​e​r​@​e​x​a​m​p​l​e​.​c​o​m
     */
    memberEmailPlaceholder: string;
    /**
     * L​o​a​d​i​n​g​ ​m​e​m​b​e​r​s​.​.​.
     */
    loadingMembers: string;
    /**
     * N​o​ ​m​e​m​b​e​r​s​ ​y​e​t​.​ ​A​d​d​ ​o​n​e​ ​a​b​o​v​e​.
     */
    noMembersYet: string;
    /**
     * R​e​m​o​v​e​ ​m​e​m​b​e​r
     */
    removeMember: string;
    /**
     * S​e​l​e​c​t​ ​a​ ​t​e​n​a​n​t​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t​ ​t​o​ ​m​a​n​a​g​e​ ​i​t​s​ ​m​e​m​b​e​r​s​.
     */
    selectTenantPrompt: string;
  };
  Forms: {
    /**
     * E​m​a​i​l
     */
    email: string;
    /**
     * E​m​a​i​l​ ​A​d​d​r​e​s​s
     */
    emailAddress: string;
    /**
     * y​o​u​@​e​x​a​m​p​l​e​.​c​o​m
     */
    emailPlaceholder: string;
    /**
     * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l
     */
    enterYourEmail: string;
    /**
     * P​a​s​s​w​o​r​d
     */
    password: string;
    /**
     * •​•​•​•​•​•​•​•
     */
    passwordPlaceholder: string;
    /**
     * P​a​s​s​w​o​r​d​ ​(​m​i​n​ ​8​ ​c​h​a​r​a​c​t​e​r​s​)
     */
    passwordMinChars: string;
    /**
     * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
     */
    confirmPassword: string;
    /**
     * F​i​r​s​t​ ​N​a​m​e
     */
    firstName: string;
    /**
     * J​o​h​n
     */
    firstNamePlaceholder: string;
    /**
     * L​a​s​t​ ​N​a​m​e
     */
    lastName: string;
    /**
     * D​o​e
     */
    lastNamePlaceholder: string;
    /**
     * N​a​m​e
     */
    name: string;
    /**
     * Y​o​u​r​ ​n​a​m​e
     */
    namePlaceholder: string;
    /**
     * V​e​r​i​f​i​c​a​t​i​o​n​ ​C​o​d​e
     */
    verificationCode: string;
    /**
     * E​n​t​e​r​ ​6​-​d​i​g​i​t​ ​c​o​d​e
     */
    verificationCodePlaceholder: string;
    /**
     * S​l​u​g
     */
    slug: string;
  };
  Errors: {
    /**
     * F​a​i​l​e​d​ ​t​o​ ​s​i​g​n​ ​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e
     */
    failedSignInGoogle: string;
    /**
     * F​a​i​l​e​d​ ​t​o​ ​s​e​n​d​ ​O​T​P​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
     */
    failedSendOtp: string;
    /**
     * U​n​a​b​l​e​ ​t​o​ ​s​e​n​d​ ​O​T​P
     */
    unableToSendOtp: string;
    /**
     * I​n​v​a​l​i​d​ ​O​T​P​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
     */
    invalidOtp: string;
    /**
     * U​n​a​b​l​e​ ​t​o​ ​v​e​r​i​f​y​ ​O​T​P
     */
    unableToVerifyOtp: string;
    /**
     * P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​b​e​f​o​r​e​ ​s​i​g​n​i​n​g​ ​i​n​.
     */
    verifyEmailBeforeSignIn: string;
    /**
     * T​h​i​s​ ​a​c​c​o​u​n​t​ ​w​a​s​ ​c​r​e​a​t​e​d​ ​w​i​t​h​ ​G​o​o​g​l​e​ ​o​r​ ​O​T​P​.​ ​U​s​e​ ​'​F​o​r​g​o​t​ ​P​a​s​s​w​o​r​d​'​ ​b​e​l​o​w​ ​t​o​ ​s​e​t​ ​a​ ​p​a​s​s​w​o​r​d​.
     */
    accountCreatedWithSocial: string;
    /**
     * I​n​v​a​l​i​d​ ​e​m​a​i​l​ ​o​r​ ​p​a​s​s​w​o​r​d​.
     */
    invalidEmailOrPassword: string;
    /**
     * P​a​s​s​w​o​r​d​s​ ​d​o​ ​n​o​t​ ​m​a​t​c​h​.
     */
    passwordsDoNotMatch: string;
    /**
     * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​8​ ​c​h​a​r​a​c​t​e​r​s​.
     */
    passwordMinLength: string;
    /**
     * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​m​o​s​t​ ​1​2​8​ ​c​h​a​r​a​c​t​e​r​s​.
     */
    passwordMaxLength: string;
    /**
     * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​u​p​p​e​r​c​a​s​e​ ​l​e​t​t​e​r​.
     */
    passwordUppercase: string;
    /**
     * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​l​o​w​e​r​c​a​s​e​ ​l​e​t​t​e​r​.
     */
    passwordLowercase: string;
    /**
     * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​n​u​m​b​e​r​.
     */
    passwordNumber: string;
    /**
     * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​.
     */
    passwordSpecialChar: string;
    /**
     * F​a​i​l​e​d​ ​t​o​ ​r​e​s​e​t​ ​p​a​s​s​w​o​r​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
     */
    failedResetPassword: string;
    /**
     * F​a​i​l​e​d​ ​t​o​ ​c​h​a​n​g​e​ ​p​a​s​s​w​o​r​d​.
     */
    failedChangePassword: string;
    /**
     * P​a​s​s​w​o​r​d​ ​c​h​a​n​g​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​.
     */
    passwordChangedSuccess: string;
    /**
     * S​i​g​n​ ​u​p​ ​f​a​i​l​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
     */
    signUpFailed: string;
    /**
     * S​i​g​n​ ​i​n​ ​f​a​i​l​e​d
     */
    signInFailed: string;
    /**
     * A​n​ ​a​c​c​o​u​n​t​ ​w​i​t​h​ ​t​h​i​s​ ​e​m​a​i​l​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.​ ​T​r​y​ ​s​i​g​n​i​n​g​ ​i​n​ ​i​n​s​t​e​a​d​ ​—​ ​i​f​ ​y​o​u​ ​u​s​e​d​ ​G​o​o​g​l​e​ ​o​r​ ​O​T​P​,​ ​y​o​u​ ​c​a​n​ ​s​e​t​ ​a​ ​p​a​s​s​w​o​r​d​ ​f​r​o​m​ ​y​o​u​r​ ​p​r​o​f​i​l​e​.
     */
    accountAlreadyExists: string;
    /**
     * {​l​a​b​e​l​}​ ​i​s​ ​r​e​q​u​i​r​e​d​.
     * @param {string} label
     */
    nameRequired: RequiredParams<"label">;
    /**
     * {​l​a​b​e​l​}​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​2​ ​c​h​a​r​a​c​t​e​r​s​.
     * @param {string} label
     */
    nameMinLength: RequiredParams<"label">;
    /**
     * {​l​a​b​e​l​}​ ​c​a​n​ ​o​n​l​y​ ​c​o​n​t​a​i​n​ ​l​e​t​t​e​r​s​,​ ​s​p​a​c​e​s​,​ ​h​y​p​h​e​n​s​,​ ​a​n​d​ ​a​p​o​s​t​r​o​p​h​e​s​.
     * @param {string} label
     */
    nameInvalidChars: RequiredParams<"label">;
    /**
     * E​m​a​i​l​ ​i​s​ ​r​e​q​u​i​r​e​d​.
     */
    emailRequired: string;
    /**
     * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​.
     */
    emailInvalid: string;
    /**
     * P​a​s​s​w​o​r​d​ ​i​s​ ​r​e​q​u​i​r​e​d​.
     */
    passwordRequired: string;
    /**
     * S​l​u​g​ ​i​s​ ​r​e​q​u​i​r​e​d
     */
    slugRequired: string;
    /**
     * N​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
     */
    nameFieldRequired: string;
    /**
     * S​l​u​g​ ​m​u​s​t​ ​b​e​ ​l​o​w​e​r​c​a​s​e​ ​l​e​t​t​e​r​s​,​ ​n​u​m​b​e​r​s​,​ ​a​n​d​ ​h​y​p​h​e​n​s​ ​o​n​l​y
     */
    slugInvalid: string;
    /**
     * N​o​ ​t​e​n​a​n​t​s​ ​a​s​s​i​g​n​e​d
     */
    noTenantsAssigned: string;
    /**
     * Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​c​c​e​s​s​ ​t​o​ ​a​n​y​ ​t​e​n​a​n​t​s​ ​y​e​t​.​ ​P​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​a​n​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​ ​t​o​ ​g​e​t​ ​a​d​d​e​d​ ​t​o​ ​a​ ​t​e​n​a​n​t​.
     */
    noTenantsMessage: string;
    /**
     * L​o​a​d​i​n​g​ ​y​o​u​r​ ​t​e​n​a​n​t​s​.​.​.
     */
    loadingYourTenants: string;
    /**
     * S​e​t​t​i​n​g​ ​u​p​ ​y​o​u​r​ ​t​e​n​a​n​t​.​.​.
     */
    settingUpTenant: string;
  };
};

export type TranslationFunctions = {
  Common: {
    /**
     * Loading...
     */
    loading: () => LocalizedString;
    /**
     * Back to Home
     */
    backToHome: () => LocalizedString;
    /**
     * Back
     */
    back: () => LocalizedString;
    /**
     * Cancel
     */
    cancel: () => LocalizedString;
    /**
     * Save
     */
    save: () => LocalizedString;
    /**
     * Add
     */
    add: () => LocalizedString;
    /**
     * Refresh
     */
    refresh: () => LocalizedString;
    /**
     * Refreshing...
     */
    refreshing: () => LocalizedString;
    /**
     * Adding...
     */
    adding: () => LocalizedString;
    /**
     * Saving...
     */
    saving: () => LocalizedString;
    /**
     * Sending...
     */
    sending: () => LocalizedString;
    /**
     * Or
     */
    or: () => LocalizedString;
    /**
     * Admin
     */
    roleAdmin: () => LocalizedString;
    /**
     * User
     */
    roleUser: () => LocalizedString;
    /**
     * You
     */
    you: () => LocalizedString;
    /**
     * Edit
     */
    edit: () => LocalizedString;
    /**
     * Delete
     */
    delete: () => LocalizedString;
    /**
     * Loading items...
     */
    loadingItems: () => LocalizedString;
    /**
     * No items yet. Add one to get started!
     */
    noItemsYet: () => LocalizedString;
    /**
     * {count} {{Item|Items}}
     */
    itemCount: (arg: { count: number }) => LocalizedString;
    /**
     * {count} {{Item|Items}} (global)
     */
    itemCountGlobal: (arg: { count: number }) => LocalizedString;
  };
  Navigation: {
    /**
     * Full Stack
     */
    fullStack: () => LocalizedString;
    /**
     * Profile & Security
     */
    profileAndSecurity: () => LocalizedString;
    /**
     * Platform Tenants
     */
    platformTenants: () => LocalizedString;
    /**
     * Manage Members
     */
    manageMembers: () => LocalizedString;
    /**
     * Sign out
     */
    signOut: () => LocalizedString;
    /**
     * Switch tenant
     */
    switchTenant: () => LocalizedString;
    /**
     * Switching...
     */
    switching: () => LocalizedString;
    /**
     * Select tenant
     */
    selectTenant: () => LocalizedString;
  };
  Home: {
    /**
     * Full Stack Boilerplate
     */
    title: () => LocalizedString;
    /**
     * NextJs (Tailwind CSS), NestJs, Expo, tRPC, Better Auth
     */
    subtitle: () => LocalizedString;
    /**
     * CRUD Demo
     */
    crudDemoTitle: () => LocalizedString;
    /**
     * Test Create, Read, Update, Delete operations with tRPC and Prisma integration. Full-stack type safety demonstration.
     */
    crudDemoDescription: () => LocalizedString;
    /**
     * Global CRUD Demo
     */
    globalCrudDemoTitle: () => LocalizedString;
    /**
     * Same as CRUD but shared across all tenants. Everyone sees and edits the same data.
     */
    globalCrudDemoDescription: () => LocalizedString;
    /**
     * Platform Tenants
     */
    platformTenantsTitle: () => LocalizedString;
    /**
     * Create, edit, and remove tenants across the platform. Super-admin only.
     */
    platformTenantsDescription: () => LocalizedString;
    /**
     * Manage tenants
     */
    manageTenants: () => LocalizedString;
    /**
     * Manage Members
     */
    manageMembersTitle: () => LocalizedString;
    /**
     * Add or remove members from tenants you administer.
     */
    manageMembersDescription: () => LocalizedString;
    /**
     * Manage members
     */
    manageMembers: () => LocalizedString;
    /**
     * Auth Demo
     */
    authDemoTitle: () => LocalizedString;
    /**
     * Test authentication with Better Auth. OAuth integration with Google, session management, and protected routes.
     */
    authDemoDescription: () => LocalizedString;
    /**
     * Try it out
     */
    tryItOut: () => LocalizedString;
    /**
     * Built with modern tools for rapid development
     */
    footer: () => LocalizedString;
  };
  Auth: {
    /**
     * Sign in
     */
    signIn: () => LocalizedString;
    /**
     * Sign in
     */
    signInTitle: () => LocalizedString;
    /**
     * Choose your preferred sign-in method
     */
    signInSubtitle: () => LocalizedString;
    /**
     * Sign in with Google
     */
    signInWithGoogle: () => LocalizedString;
    /**
     * Sign in with Email OTP
     */
    signInWithEmailOtp: () => LocalizedString;
    /**
     * Or with Email & Password
     */
    orWithEmailPassword: () => LocalizedString;
    /**
     * Sign in with Email & Password
     */
    signInWithEmailPassword: () => LocalizedString;
    /**
     * Signing in...
     */
    signingIn: () => LocalizedString;
    /**
     * Sign up
     */
    signUp: () => LocalizedString;
    /**
     * Create an account
     */
    signUpTitle: () => LocalizedString;
    /**
     * Sign up with your email and password
     */
    signUpSubtitle: () => LocalizedString;
    /**
     * Sign up with Email & Password
     */
    signUpWithEmailPassword: () => LocalizedString;
    /**
     * Creating account...
     */
    creatingAccount: () => LocalizedString;
    /**
     * Don't have an account?
     */
    dontHaveAccount: () => LocalizedString;
    /**
     * Already have an account?
     */
    alreadyHaveAccount: () => LocalizedString;
    /**
     * Forgot Password?
     */
    forgotPassword: () => LocalizedString;
    /**
     * Forgot Password
     */
    forgotPasswordTitle: () => LocalizedString;
    /**
     * Enter your email to receive a password reset link
     */
    forgotPasswordSubtitle: () => LocalizedString;
    /**
     * Check your inbox
     */
    checkYourInbox: () => LocalizedString;
    /**
     * Send Reset Link
     */
    sendResetLink: () => LocalizedString;
    /**
     * Back to Sign In
     */
    backToSignIn: () => LocalizedString;
    /**
     * If an account exists with this email, you'll receive a link to set your password.
     */
    resetLinkSentMessage: () => LocalizedString;
    /**
     * Set Your Password
     */
    setYourPassword: () => LocalizedString;
    /**
     * Enter a new password for your account
     */
    setPasswordSubtitle: () => LocalizedString;
    /**
     * Set Password
     */
    setPassword: () => LocalizedString;
    /**
     * Setting password...
     */
    settingPassword: () => LocalizedString;
    /**
     * Invalid or Expired Link
     */
    invalidOrExpiredLink: () => LocalizedString;
    /**
     * This password reset link is invalid or has expired. Please request a new one.
     */
    invalidOrExpiredLinkMessage: () => LocalizedString;
    /**
     * Request New Link
     */
    requestNewLink: () => LocalizedString;
    /**
     * Verification Failed
     */
    verificationFailed: () => LocalizedString;
    /**
     * This verification link has expired. Please try signing in again to receive a new verification email.
     */
    verificationFailedExpired: () => LocalizedString;
    /**
     * This verification link is invalid. Please try signing in again to receive a new verification email.
     */
    verificationFailedInvalid: () => LocalizedString;
    /**
     * Email Verified!
     */
    emailVerified: () => LocalizedString;
    /**
     * Your email has been verified successfully. Redirecting to home...
     */
    emailVerifiedMessage: () => LocalizedString;
    /**
     * Go to Home now
     */
    goToHome: () => LocalizedString;
    /**
     * Go to Sign In
     */
    goToSignIn: () => LocalizedString;
    /**
     * Send OTP
     */
    sendOtp: () => LocalizedString;
    /**
     * Verify OTP
     */
    verifyOtp: () => LocalizedString;
    /**
     * Verifying...
     */
    verifying: () => LocalizedString;
    /**
     * Change Email
     */
    changeEmail: () => LocalizedString;
    /**
     * We sent a verification code to {email}
     */
    otpSentTo: (arg: { email: string }) => LocalizedString;
    /**
     * We've sent a verification email to {email}. Please check your inbox and click the link to verify your account before signing in.
     */
    checkInboxMessage: (arg: { email: string }) => LocalizedString;
    /**
     * Password set successfully. You can now sign in.
     */
    passwordSetSuccess: () => LocalizedString;
    /**
     * Sign in required
     */
    signInRequired: () => LocalizedString;
    /**
     * You need to be authenticated to access this application.
     */
    signInRequiredMessage: () => LocalizedString;
    /**
     * Better Auth Demo
     */
    betterAuthDemo: () => LocalizedString;
    /**
     * Welcome back!
     */
    welcomeBack: () => LocalizedString;
    /**
     * Sign in to continue
     */
    signInToContinue: () => LocalizedString;
    /**
     * You are signed in
     */
    youAreSignedIn: () => LocalizedString;
    /**
     * User Information
     */
    userInformation: () => LocalizedString;
    /**
     * Sign Out
     */
    signOutButton: () => LocalizedString;
    /**
     * Or Email & Password
     */
    orEmailPassword: () => LocalizedString;
    /**
     * Resend verification email
     */
    resendVerificationEmail: () => LocalizedString;
    /**
     * Verification email sent! Check your inbox.
     */
    verificationEmailSent: () => LocalizedString;
    /**
     * Min 8 characters with uppercase, lowercase, number, and special character.
     */
    passwordMinChars: () => LocalizedString;
  };
  Dashboard: {
    /**
     * Platform Tenants
     */
    platformTenantsTitle: () => LocalizedString;
    /**
     * Create, edit, and remove tenants. Super-admin only.
     */
    platformTenantsSubtitle: () => LocalizedString;
    /**
     * You must be logged in to access this page.
     */
    mustBeLoggedIn: () => LocalizedString;
    /**
     * Super-admin access required. Your email must be in SUPER_ADMIN_EMAILS.
     */
    superAdminRequired: () => LocalizedString;
    /**
     * Add tenant
     */
    addTenant: () => LocalizedString;
    /**
     * Slug (a-z, 0-9, hyphens)
     */
    slugLabel: () => LocalizedString;
    /**
     * e.g. acme-corp
     */
    slugPlaceholder: () => LocalizedString;
    /**
     * e.g. Acme Corp
     */
    namePlaceholder: () => LocalizedString;
    /**
     * {count} tenant{{s|}}
     */
    tenantCount: (arg: { count: number }) => LocalizedString;
    /**
     * Loading tenants...
     */
    loadingTenants: () => LocalizedString;
    /**
     * No tenants yet. Add one above.
     */
    noTenantsYet: () => LocalizedString;
    /**
     * Refresh list
     */
    refreshList: () => LocalizedString;
    /**
     * Delete tenant "{slug}"? This cannot be undone.
     */
    deleteConfirm: (arg: { slug: string }) => LocalizedString;
    /**
     * Dual Database CRUD Demo
     */
    dualDatabaseCrudDemo: () => LocalizedString;
    /**
     * Side-by-side comparison of Mongoose (MongoDB) and Prisma (PostgreSQL)
     */
    crudDemoSubtitle: () => LocalizedString;
    /**
     * NextJs (TailwindCSS) • NestJs • tRPC • Transactions
     */
    crudDemoTechStack: () => LocalizedString;
    /**
     * → Tenant Dashboard (super-admin)
     */
    tenantDashboardLink: () => LocalizedString;
    /**
     * Global CRUD Demo
     */
    globalCrudDemoTitle: () => LocalizedString;
    /**
     * Same as CRUD but shared across all tenants. Everyone sees and edits the same data.
     */
    globalCrudDemoSubtitle: () => LocalizedString;
    /**
     * Mongoose (MongoDB) & Prisma (PostgreSQL) • No tenant scope
     */
    globalCrudDemoTechStack: () => LocalizedString;
    /**
     * Add text here
     */
    addTextPlaceholder: () => LocalizedString;
  };
  Settings: {
    /**
     * Profile
     */
    profileTitle: () => LocalizedString;
    /**
     * Manage your account security and linked sign-in methods.
     */
    profileSubtitle: () => LocalizedString;
    /**
     * Your email is not verified
     */
    emailNotVerified: () => LocalizedString;
    /**
     * Please verify your email to access all features.
     */
    verifyEmailPrompt: () => LocalizedString;
    /**
     * Account Info
     */
    accountInfo: () => LocalizedString;
    /**
     * Linked Accounts
     */
    linkedAccounts: () => LocalizedString;
    /**
     * Google
     */
    google: () => LocalizedString;
    /**
     * Connected
     */
    connected: () => LocalizedString;
    /**
     * Connect Google
     */
    connectGoogle: () => LocalizedString;
    /**
     * Email & Password
     */
    emailAndPassword: () => LocalizedString;
    /**
     * Password set
     */
    passwordSet: () => LocalizedString;
    /**
     * Not set
     */
    notSet: () => LocalizedString;
    /**
     * Password
     */
    passwordTitle: () => LocalizedString;
    /**
     * Change Password
     */
    changePassword: () => LocalizedString;
    /**
     * Current Password
     */
    currentPassword: () => LocalizedString;
    /**
     * New Password (min 8 characters)
     */
    newPasswordLabel: () => LocalizedString;
    /**
     * Confirm New Password
     */
    confirmNewPassword: () => LocalizedString;
    /**
     * Save Password
     */
    savePassword: () => LocalizedString;
    /**
     * Add a password to sign in without Google or OTP.
     */
    addPasswordDescription: () => LocalizedString;
    /**
     * Check your inbox to set your password.
     */
    checkInboxForPassword: () => LocalizedString;
    /**
     * Manage Members
     */
    manageMembersTitle: () => LocalizedString;
    /**
     * Add or remove members from your tenants.
     */
    manageMembersSubtitle: () => LocalizedString;
    /**
     * No admin access
     */
    noAdminAccess: () => LocalizedString;
    /**
     * You don't have admin access to any tenants.
     */
    noAdminAccessMessage: () => LocalizedString;
    /**
     * Your tenants ({count})
     */
    yourTenants: (arg: { count: number }) => LocalizedString;
    /**
     * Members of {name}
     */
    membersOf: (arg: { name: string }) => LocalizedString;
    /**
     * Add member
     */
    addMember: () => LocalizedString;
    /**
     * user@example.com
     */
    memberEmailPlaceholder: () => LocalizedString;
    /**
     * Loading members...
     */
    loadingMembers: () => LocalizedString;
    /**
     * No members yet. Add one above.
     */
    noMembersYet: () => LocalizedString;
    /**
     * Remove member
     */
    removeMember: () => LocalizedString;
    /**
     * Select a tenant from the list to manage its members.
     */
    selectTenantPrompt: () => LocalizedString;
  };
  Forms: {
    /**
     * Email
     */
    email: () => LocalizedString;
    /**
     * Email Address
     */
    emailAddress: () => LocalizedString;
    /**
     * you@example.com
     */
    emailPlaceholder: () => LocalizedString;
    /**
     * Enter your email
     */
    enterYourEmail: () => LocalizedString;
    /**
     * Password
     */
    password: () => LocalizedString;
    /**
     * ••••••••
     */
    passwordPlaceholder: () => LocalizedString;
    /**
     * Password (min 8 characters)
     */
    passwordMinChars: () => LocalizedString;
    /**
     * Confirm Password
     */
    confirmPassword: () => LocalizedString;
    /**
     * First Name
     */
    firstName: () => LocalizedString;
    /**
     * John
     */
    firstNamePlaceholder: () => LocalizedString;
    /**
     * Last Name
     */
    lastName: () => LocalizedString;
    /**
     * Doe
     */
    lastNamePlaceholder: () => LocalizedString;
    /**
     * Name
     */
    name: () => LocalizedString;
    /**
     * Your name
     */
    namePlaceholder: () => LocalizedString;
    /**
     * Verification Code
     */
    verificationCode: () => LocalizedString;
    /**
     * Enter 6-digit code
     */
    verificationCodePlaceholder: () => LocalizedString;
    /**
     * Slug
     */
    slug: () => LocalizedString;
  };
  Errors: {
    /**
     * Failed to sign in with Google
     */
    failedSignInGoogle: () => LocalizedString;
    /**
     * Failed to send OTP. Please try again.
     */
    failedSendOtp: () => LocalizedString;
    /**
     * Unable to send OTP
     */
    unableToSendOtp: () => LocalizedString;
    /**
     * Invalid OTP. Please try again.
     */
    invalidOtp: () => LocalizedString;
    /**
     * Unable to verify OTP
     */
    unableToVerifyOtp: () => LocalizedString;
    /**
     * Please verify your email address before signing in.
     */
    verifyEmailBeforeSignIn: () => LocalizedString;
    /**
     * This account was created with Google or OTP. Use 'Forgot Password' below to set a password.
     */
    accountCreatedWithSocial: () => LocalizedString;
    /**
     * Invalid email or password.
     */
    invalidEmailOrPassword: () => LocalizedString;
    /**
     * Passwords do not match.
     */
    passwordsDoNotMatch: () => LocalizedString;
    /**
     * Password must be at least 8 characters.
     */
    passwordMinLength: () => LocalizedString;
    /**
     * Password must be at most 128 characters.
     */
    passwordMaxLength: () => LocalizedString;
    /**
     * Password must contain at least one uppercase letter.
     */
    passwordUppercase: () => LocalizedString;
    /**
     * Password must contain at least one lowercase letter.
     */
    passwordLowercase: () => LocalizedString;
    /**
     * Password must contain at least one number.
     */
    passwordNumber: () => LocalizedString;
    /**
     * Password must contain at least one special character.
     */
    passwordSpecialChar: () => LocalizedString;
    /**
     * Failed to reset password. Please try again.
     */
    failedResetPassword: () => LocalizedString;
    /**
     * Failed to change password.
     */
    failedChangePassword: () => LocalizedString;
    /**
     * Password changed successfully.
     */
    passwordChangedSuccess: () => LocalizedString;
    /**
     * Sign up failed. Please try again.
     */
    signUpFailed: () => LocalizedString;
    /**
     * Sign in failed
     */
    signInFailed: () => LocalizedString;
    /**
     * An account with this email already exists. Try signing in instead — if you used Google or OTP, you can set a password from your profile.
     */
    accountAlreadyExists: () => LocalizedString;
    /**
     * {label} is required.
     */
    nameRequired: (arg: { label: string }) => LocalizedString;
    /**
     * {label} must be at least 2 characters.
     */
    nameMinLength: (arg: { label: string }) => LocalizedString;
    /**
     * {label} can only contain letters, spaces, hyphens, and apostrophes.
     */
    nameInvalidChars: (arg: { label: string }) => LocalizedString;
    /**
     * Email is required.
     */
    emailRequired: () => LocalizedString;
    /**
     * Please enter a valid email address.
     */
    emailInvalid: () => LocalizedString;
    /**
     * Password is required.
     */
    passwordRequired: () => LocalizedString;
    /**
     * Slug is required
     */
    slugRequired: () => LocalizedString;
    /**
     * Name is required
     */
    nameFieldRequired: () => LocalizedString;
    /**
     * Slug must be lowercase letters, numbers, and hyphens only
     */
    slugInvalid: () => LocalizedString;
    /**
     * No tenants assigned
     */
    noTenantsAssigned: () => LocalizedString;
    /**
     * You don't have access to any tenants yet. Please contact an administrator to get added to a tenant.
     */
    noTenantsMessage: () => LocalizedString;
    /**
     * Loading your tenants...
     */
    loadingYourTenants: () => LocalizedString;
    /**
     * Setting up your tenant...
     */
    settingUpTenant: () => LocalizedString;
  };
};

export type Formatters = {};
