import { initTRPC } from "@trpc/server";
import {
  ZAddMemberRequest,
  ZAddMemberResponse,
  ZCrudCreateRequest,
  ZCrudCreateResponse,
  ZCrudDeleteRequest,
  ZCrudDeleteResponse,
  ZCrudFindAllRequest,
  ZCrudFindAllResponse,
  ZCrudFindOneRequest,
  ZCrudFindOneResponse,
  ZCrudUpdateRequest,
  ZCrudUpdateResponse,
  ZGdprDeleteAccountRequest,
  ZGdprDeleteAccountResponse,
  ZGdprMyDataResponse,
  ZGdprUpdateProfileRequest,
  ZGdprUpdateProfileResponse,
  ZGlobalCrudCreateRequest,
  ZGlobalCrudCreateResponse,
  ZGlobalCrudDeleteRequest,
  ZGlobalCrudDeleteResponse,
  ZGlobalCrudFindAllRequest,
  ZGlobalCrudFindAllResponse,
  ZGlobalCrudFindOneRequest,
  ZGlobalCrudFindOneResponse,
  ZGlobalCrudUpdateRequest,
  ZGlobalCrudUpdateResponse,
  ZListMembersRequest,
  ZListMembersResponse,
  ZMyTenantsResponse,
  ZRemoveMemberRequest,
  ZRemoveMemberResponse,
  ZSwitchTenantRequest,
  ZSwitchTenantResponse,
  ZTenantCreateRequest,
  ZTenantCreateResponse,
  ZTenantDeleteRequest,
  ZTenantDeleteResponse,
  ZTenantFindAllResponse,
  ZTenantFindOneRequest,
  ZTenantFindOneResponse,
  ZTenantMetaIsSuperAdminResponse,
  ZTenantUpdateRequest,
  ZTenantUpdateResponse,
} from "@repo/contracts";

const t = initTRPC.create();
const publicProcedure = t.procedure;

const PLACEHOLDER = async () => "PLACEHOLDER_DO_NOT_REMOVE" as any;

const appRouter = t.router({
  crud: t.router({
    createCrudMongo: publicProcedure.input(ZCrudCreateRequest).output(ZCrudCreateResponse).mutation(PLACEHOLDER),
    findAllMongo: publicProcedure.input(ZCrudFindAllRequest).output(ZCrudFindAllResponse).query(PLACEHOLDER),
    findOneCrudMongo: publicProcedure.input(ZCrudFindOneRequest).output(ZCrudFindOneResponse).query(PLACEHOLDER),
    updateCrudMongo: publicProcedure.input(ZCrudUpdateRequest).output(ZCrudUpdateResponse).mutation(PLACEHOLDER),
    deleteCrudMongo: publicProcedure.input(ZCrudDeleteRequest).output(ZCrudDeleteResponse).mutation(PLACEHOLDER),
    createCrudPrisma: publicProcedure.input(ZCrudCreateRequest).output(ZCrudCreateResponse).mutation(PLACEHOLDER),
    findAllPrisma: publicProcedure.input(ZCrudFindAllRequest).output(ZCrudFindAllResponse).query(PLACEHOLDER),
    findOneCrudPrisma: publicProcedure.input(ZCrudFindOneRequest).output(ZCrudFindOneResponse).query(PLACEHOLDER),
    updateCrudPrisma: publicProcedure.input(ZCrudUpdateRequest).output(ZCrudUpdateResponse).mutation(PLACEHOLDER),
    deleteCrudPrisma: publicProcedure.input(ZCrudDeleteRequest).output(ZCrudDeleteResponse).mutation(PLACEHOLDER),
  }),
  gdpr: t.router({
    myData: publicProcedure.output(ZGdprMyDataResponse).query(PLACEHOLDER),
    exportData: publicProcedure.output(ZGdprMyDataResponse).query(PLACEHOLDER),
    updateProfile: publicProcedure.input(ZGdprUpdateProfileRequest).output(ZGdprUpdateProfileResponse).mutation(PLACEHOLDER),
    deleteAccount: publicProcedure.input(ZGdprDeleteAccountRequest).output(ZGdprDeleteAccountResponse).mutation(PLACEHOLDER),
  }),
  globalCrud: t.router({
    createMongo: publicProcedure.input(ZGlobalCrudCreateRequest).output(ZGlobalCrudCreateResponse).mutation(PLACEHOLDER),
    findAllMongo: publicProcedure.input(ZGlobalCrudFindAllRequest).output(ZGlobalCrudFindAllResponse).query(PLACEHOLDER),
    findOneMongo: publicProcedure.input(ZGlobalCrudFindOneRequest).output(ZGlobalCrudFindOneResponse).query(PLACEHOLDER),
    updateMongo: publicProcedure.input(ZGlobalCrudUpdateRequest).output(ZGlobalCrudUpdateResponse).mutation(PLACEHOLDER),
    deleteMongo: publicProcedure.input(ZGlobalCrudDeleteRequest).output(ZGlobalCrudDeleteResponse).mutation(PLACEHOLDER),
    createPrisma: publicProcedure.input(ZGlobalCrudCreateRequest).output(ZGlobalCrudCreateResponse).mutation(PLACEHOLDER),
    findAllPrisma: publicProcedure.input(ZGlobalCrudFindAllRequest).output(ZGlobalCrudFindAllResponse).query(PLACEHOLDER),
    findOnePrisma: publicProcedure.input(ZGlobalCrudFindOneRequest).output(ZGlobalCrudFindOneResponse).query(PLACEHOLDER),
    updatePrisma: publicProcedure.input(ZGlobalCrudUpdateRequest).output(ZGlobalCrudUpdateResponse).mutation(PLACEHOLDER),
    deletePrisma: publicProcedure.input(ZGlobalCrudDeleteRequest).output(ZGlobalCrudDeleteResponse).mutation(PLACEHOLDER),
  }),
  tenant: t.router({
    isSuperAdmin: publicProcedure.output(ZTenantMetaIsSuperAdminResponse).query(PLACEHOLDER),
    myTenants: publicProcedure.output(ZMyTenantsResponse).query(PLACEHOLDER),
    switchTenant: publicProcedure.input(ZSwitchTenantRequest).output(ZSwitchTenantResponse).mutation(PLACEHOLDER),
    create: publicProcedure.input(ZTenantCreateRequest).output(ZTenantCreateResponse).mutation(PLACEHOLDER),
    findAll: publicProcedure.output(ZTenantFindAllResponse).query(PLACEHOLDER),
    findOne: publicProcedure.input(ZTenantFindOneRequest).output(ZTenantFindOneResponse).query(PLACEHOLDER),
    update: publicProcedure.input(ZTenantUpdateRequest).output(ZTenantUpdateResponse).mutation(PLACEHOLDER),
    delete: publicProcedure.input(ZTenantDeleteRequest).output(ZTenantDeleteResponse).mutation(PLACEHOLDER),
    addMember: publicProcedure.input(ZAddMemberRequest).output(ZAddMemberResponse).mutation(PLACEHOLDER),
    removeMember: publicProcedure.input(ZRemoveMemberRequest).output(ZRemoveMemberResponse).mutation(PLACEHOLDER),
    listMembers: publicProcedure.input(ZListMembersRequest).output(ZListMembersResponse).query(PLACEHOLDER),
  }),
});

export type AppRouter = typeof appRouter;